<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hongyue Kang">
<meta name="author" content="Kelly Schoonderwoerd">
<meta name="author" content="Viola Ebermannová">

<title>Urban stream restoration – Teplica (Senica, SK)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-17a5f7109c529cfde00c5b46f211b69b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul>
  <li><a href="#key-words" id="toc-key-words" class="nav-link" data-scroll-target="#key-words">Key words:</a></li>
  <li><a href="#colophon" id="toc-colophon" class="nav-link" data-scroll-target="#colophon">Colophon</a>
  <ul>
  <li><a href="#students-contact-roles-and-contributions" id="toc-students-contact-roles-and-contributions" class="nav-link" data-scroll-target="#students-contact-roles-and-contributions">Students – contact, roles and contributions</a></li>
  <li><a href="#course-information" id="toc-course-information" class="nav-link" data-scroll-target="#course-information">Course information</a></li>
  </ul></li>
  <li><a href="#introduction-of-the-case-problem-statement-and-objectives" id="toc-introduction-of-the-case-problem-statement-and-objectives" class="nav-link" data-scroll-target="#introduction-of-the-case-problem-statement-and-objectives">Introduction of the case, problem statement, and objectives</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul>
  <li><a href="#reproducibility-self-assessment" id="toc-reproducibility-self-assessment" class="nav-link" data-scroll-target="#reproducibility-self-assessment">Reproducibility self assessment</a></li>
  </ul></li>
  <li><a href="#mcda" id="toc-mcda" class="nav-link" data-scroll-target="#mcda">MCDA</a>
  <ul>
  <li><a href="#explanation-of-how-mcda-works" id="toc-explanation-of-how-mcda-works" class="nav-link" data-scroll-target="#explanation-of-how-mcda-works">Explanation of how MCDA works</a></li>
  <li><a href="#selecting-objectives-and-criteria-three-pillar-system" id="toc-selecting-objectives-and-criteria-three-pillar-system" class="nav-link" data-scroll-target="#selecting-objectives-and-criteria-three-pillar-system">Selecting objectives and criteria – three pillar system</a>
  <ul>
  <li><a href="#detailed-research-structure" id="toc-detailed-research-structure" class="nav-link" data-scroll-target="#detailed-research-structure">Detailed research structure</a></li>
  </ul></li>
  <li><a href="#weighting" id="toc-weighting" class="nav-link" data-scroll-target="#weighting">Weighting</a></li>
  <li><a href="#analysis-geometry" id="toc-analysis-geometry" class="nav-link" data-scroll-target="#analysis-geometry">Analysis geometry</a>
  <ul>
  <li><a href="#principle-1-úses" id="toc-principle-1-úses" class="nav-link" data-scroll-target="#principle-1-úses">Principle 1: ÚSES</a></li>
  <li><a href="#principle-2-flood-plain" id="toc-principle-2-flood-plain" class="nav-link" data-scroll-target="#principle-2-flood-plain">Principle 2: Flood plain</a></li>
  <li><a href="#principle-3-morphology" id="toc-principle-3-morphology" class="nav-link" data-scroll-target="#principle-3-morphology">Principle 3: Morphology</a></li>
  <li><a href="#principle-4-parcelation" id="toc-principle-4-parcelation" class="nav-link" data-scroll-target="#principle-4-parcelation">Principle 4: Parcelation</a></li>
  <li><a href="#land-cover-classification" id="toc-land-cover-classification" class="nav-link" data-scroll-target="#land-cover-classification">Land cover classification</a></li>
  </ul></li>
  <li><a href="#data-structure" id="toc-data-structure" class="nav-link" data-scroll-target="#data-structure">Data structure</a></li>
  <li><a href="#biodiversity" id="toc-biodiversity" class="nav-link" data-scroll-target="#biodiversity">Biodiversity</a>
  <ul>
  <li><a href="#b1uses-which-spaces-should-be-prioritised-because-of-their-connectivity-to-úses" id="toc-b1uses-which-spaces-should-be-prioritised-because-of-their-connectivity-to-úses" class="nav-link" data-scroll-target="#b1uses-which-spaces-should-be-prioritised-because-of-their-connectivity-to-úses"><em>B1uses</em> – Which spaces should be prioritised because of their connectivity to ÚSES?</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#aggregation-and-normalisation" id="toc-aggregation-and-normalisation" class="nav-link" data-scroll-target="#aggregation-and-normalisation">Aggregation and normalisation</a></li>
  </ul></li>
  <li><a href="#b2pot-which-spaces-should-be-prioritised-based-on-ecological-quality-improvement-potential-and-feasibility-of-intervention" id="toc-b2pot-which-spaces-should-be-prioritised-based-on-ecological-quality-improvement-potential-and-feasibility-of-intervention" class="nav-link" data-scroll-target="#b2pot-which-spaces-should-be-prioritised-based-on-ecological-quality-improvement-potential-and-feasibility-of-intervention"><em>B2pot</em> – Which spaces should be prioritised based on ecological quality improvement potential and feasibility of intervention?</a>
  <ul class="collapse">
  <li><a href="#data-1" id="toc-data-1" class="nav-link" data-scroll-target="#data-1">Data</a></li>
  <li><a href="#aggregation-and-normalisation-1" id="toc-aggregation-and-normalisation-1" class="nav-link" data-scroll-target="#aggregation-and-normalisation-1">Aggregation and normalisation</a></li>
  </ul></li>
  <li><a href="#b3ndvi-which-spaces-should-be-prioritized-based-on-current-state-of-the-vegetation" id="toc-b3ndvi-which-spaces-should-be-prioritized-based-on-current-state-of-the-vegetation" class="nav-link" data-scroll-target="#b3ndvi-which-spaces-should-be-prioritized-based-on-current-state-of-the-vegetation"><em>B3ndvi</em> – Which spaces should be prioritized based on current state of the vegetation?</a>
  <ul class="collapse">
  <li><a href="#data-2" id="toc-data-2" class="nav-link" data-scroll-target="#data-2">Data</a></li>
  <li><a href="#aggregation-and-normalisation-2" id="toc-aggregation-and-normalisation-2" class="nav-link" data-scroll-target="#aggregation-and-normalisation-2">Aggregation and normalisation</a></li>
  </ul></li>
  <li><a href="#weighting-1" id="toc-weighting-1" class="nav-link" data-scroll-target="#weighting-1">Weighting</a></li>
  <li><a href="#biodiversity-conclusion" id="toc-biodiversity-conclusion" class="nav-link" data-scroll-target="#biodiversity-conclusion">Biodiversity conclusion</a></li>
  </ul></li>
  <li><a href="#climate-adaptation" id="toc-climate-adaptation" class="nav-link" data-scroll-target="#climate-adaptation">Climate adaptation</a>
  <ul>
  <li><a href="#ca1temp-which-spaces-should-be-prioritized-for-interventions-aimed-at-cooling-the-area-down" id="toc-ca1temp-which-spaces-should-be-prioritized-for-interventions-aimed-at-cooling-the-area-down" class="nav-link" data-scroll-target="#ca1temp-which-spaces-should-be-prioritized-for-interventions-aimed-at-cooling-the-area-down"><em>CA1temp</em> – Which spaces should be prioritized for interventions aimed at cooling the area down?</a>
  <ul class="collapse">
  <li><a href="#data-3" id="toc-data-3" class="nav-link" data-scroll-target="#data-3">Data</a></li>
  <li><a href="#weigting-and-normalisation" id="toc-weigting-and-normalisation" class="nav-link" data-scroll-target="#weigting-and-normalisation">Weigting and normalisation</a></li>
  </ul></li>
  <li><a href="#ca2soil-where-does-the-soil-have-high-potential-for-water-retention" id="toc-ca2soil-where-does-the-soil-have-high-potential-for-water-retention" class="nav-link" data-scroll-target="#ca2soil-where-does-the-soil-have-high-potential-for-water-retention"><em>CA2soil</em> – Where does the soil have high potential for water retention?</a>
  <ul class="collapse">
  <li><a href="#data-4" id="toc-data-4" class="nav-link" data-scroll-target="#data-4">Data</a></li>
  <li><a href="#aggregation-and-normalisation-3" id="toc-aggregation-and-normalisation-3" class="nav-link" data-scroll-target="#aggregation-and-normalisation-3">Aggregation and normalisation</a></li>
  </ul></li>
  <li><a href="#weighting-2" id="toc-weighting-2" class="nav-link" data-scroll-target="#weighting-2">Weighting</a></li>
  <li><a href="#climate-adaptation-conclusion" id="toc-climate-adaptation-conclusion" class="nav-link" data-scroll-target="#climate-adaptation-conclusion">Climate adaptation conclusion</a></li>
  </ul></li>
  <li><a href="#quality-of-life" id="toc-quality-of-life" class="nav-link" data-scroll-target="#quality-of-life">Quality of life</a>
  <ul>
  <li><a href="#ql1acl-where-is-potential-for-community-functions" id="toc-ql1acl-where-is-potential-for-community-functions" class="nav-link" data-scroll-target="#ql1acl-where-is-potential-for-community-functions"><em>QL1acl</em> – Where is potential for community functions?</a>
  <ul class="collapse">
  <li><a href="#data-5" id="toc-data-5" class="nav-link" data-scroll-target="#data-5">Data</a></li>
  <li><a href="#weighting-and-normalisation" id="toc-weighting-and-normalisation" class="nav-link" data-scroll-target="#weighting-and-normalisation">Weighting and normalisation</a></li>
  </ul></li>
  <li><a href="#ql2acg-where-is-potential-for-central-functions" id="toc-ql2acg-where-is-potential-for-central-functions" class="nav-link" data-scroll-target="#ql2acg-where-is-potential-for-central-functions"><em>QL2acg</em> – Where is potential for “central” functions?</a>
  <ul class="collapse">
  <li><a href="#data-6" id="toc-data-6" class="nav-link" data-scroll-target="#data-6">Data</a></li>
  <li><a href="#aggregation-and-normalisation-4" id="toc-aggregation-and-normalisation-4" class="nav-link" data-scroll-target="#aggregation-and-normalisation-4">Aggregation and normalisation</a></li>
  </ul></li>
  <li><a href="#ql3gr-where-is-a-large-need-for-green" id="toc-ql3gr-where-is-a-large-need-for-green" class="nav-link" data-scroll-target="#ql3gr-where-is-a-large-need-for-green"><em>QL3gr</em> – Where is a large need for green?</a>
  <ul class="collapse">
  <li><a href="#data-7" id="toc-data-7" class="nav-link" data-scroll-target="#data-7">Data</a></li>
  <li><a href="#aggregation-and-normalisation-5" id="toc-aggregation-and-normalisation-5" class="nav-link" data-scroll-target="#aggregation-and-normalisation-5">Aggregation and normalisation</a></li>
  </ul></li>
  <li><a href="#weighting-3" id="toc-weighting-3" class="nav-link" data-scroll-target="#weighting-3">Weighting</a></li>
  <li><a href="#quality-of-life-conclusion" id="toc-quality-of-life-conclusion" class="nav-link" data-scroll-target="#quality-of-life-conclusion">Quality of life conclusion</a></li>
  </ul></li>
  <li><a href="#mcda-conclusion" id="toc-mcda-conclusion" class="nav-link" data-scroll-target="#mcda-conclusion">MCDA conclusion</a></li>
  </ul></li>
  <li><a href="#typology-construction" id="toc-typology-construction" class="nav-link" data-scroll-target="#typology-construction">Typology Construction</a>
  <ul>
  <li><a href="#clustering" id="toc-clustering" class="nav-link" data-scroll-target="#clustering">Clustering</a>
  <ul>
  <li><a href="#focus-area-and-variables" id="toc-focus-area-and-variables" class="nav-link" data-scroll-target="#focus-area-and-variables">Focus area and variables</a></li>
  </ul></li>
  <li><a href="#workflow" id="toc-workflow" class="nav-link" data-scroll-target="#workflow">Workflow</a>
  <ul>
  <li><a href="#step-1.-load-r-packages-and-data" id="toc-step-1.-load-r-packages-and-data" class="nav-link" data-scroll-target="#step-1.-load-r-packages-and-data">Step 1. Load R packages and data</a></li>
  <li><a href="#step-2.-standardization" id="toc-step-2.-standardization" class="nav-link" data-scroll-target="#step-2.-standardization">Step 2. Standardization</a></li>
  <li><a href="#step-3-determine-the-optimal-k" id="toc-step-3-determine-the-optimal-k" class="nav-link" data-scroll-target="#step-3-determine-the-optimal-k">Step 3: Determine the optimal K</a></li>
  <li><a href="#step-4.-run-k-means-clustering" id="toc-step-4.-run-k-means-clustering" class="nav-link" data-scroll-target="#step-4.-run-k-means-clustering">Step 4. Run K-Means clustering</a></li>
  <li><a href="#step-5.-interpret-cluster-centers" id="toc-step-5.-interpret-cluster-centers" class="nav-link" data-scroll-target="#step-5.-interpret-cluster-centers">Step 5. Interpret cluster centers</a></li>
  <li><a href="#step-6.-optional-calculate-distance-to-cluster-center" id="toc-step-6.-optional-calculate-distance-to-cluster-center" class="nav-link" data-scroll-target="#step-6.-optional-calculate-distance-to-cluster-center">Step 6. (Optional) Calculate distance to cluster center</a></li>
  </ul></li>
  <li><a href="#typology-construction-conclusion" id="toc-typology-construction-conclusion" class="nav-link" data-scroll-target="#typology-construction-conclusion">Typology Construction conclusion</a>
  <ul>
  <li><a href="#typology-description" id="toc-typology-description" class="nav-link" data-scroll-target="#typology-description">Typology description</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul>
  <li><a href="#tying-the-two-analysis-methods-together" id="toc-tying-the-two-analysis-methods-together" class="nav-link" data-scroll-target="#tying-the-two-analysis-methods-together">Tying the two analysis methods together</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul>
  <li><a href="#analysis-geometry-1" id="toc-analysis-geometry-1" class="nav-link" data-scroll-target="#analysis-geometry-1">Analysis geometry</a></li>
  <li><a href="#mcda-criteria-selection" id="toc-mcda-criteria-selection" class="nav-link" data-scroll-target="#mcda-criteria-selection">MCDA criteria selection</a></li>
  <li><a href="#other-notes" id="toc-other-notes" class="nav-link" data-scroll-target="#other-notes">Other notes</a></li>
  <li><a href="#significant-flaws-in-analysis" id="toc-significant-flaws-in-analysis" class="nav-link" data-scroll-target="#significant-flaws-in-analysis">Significant flaws in analysis</a></li>
  </ul></li>
  <li><a href="#reflection" id="toc-reflection" class="nav-link" data-scroll-target="#reflection">Reflection</a>
  <ul>
  <li><a href="#violas-reflection-on-teamwork" id="toc-violas-reflection-on-teamwork" class="nav-link" data-scroll-target="#violas-reflection-on-teamwork">Viola’s reflection on teamwork</a></li>
  <li><a href="#kellys-reflection-on-teamwork" id="toc-kellys-reflection-on-teamwork" class="nav-link" data-scroll-target="#kellys-reflection-on-teamwork">Kelly’s reflection on teamwork</a></li>
  </ul></li>
  <li><a href="#conclusion-1" id="toc-conclusion-1" class="nav-link" data-scroll-target="#conclusion-1">Conclusion</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix">Appendix</a>
  <ul>
  <li><a href="#space-syntax-analysis" id="toc-space-syntax-analysis" class="nav-link" data-scroll-target="#space-syntax-analysis">Space syntax analysis</a></li>
  </ul></li>
  <li><a href="#sources" id="toc-sources" class="nav-link" data-scroll-target="#sources">Sources</a>
  <ul>
  <li><a href="#literature" id="toc-literature" class="nav-link" data-scroll-target="#literature">Literature</a></li>
  <li><a href="#map-layers" id="toc-map-layers" class="nav-link" data-scroll-target="#map-layers">Map layers</a></li>
  <li><a href="#images" id="toc-images" class="nav-link" data-scroll-target="#images">Images</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Urban stream restoration – Teplica (Senica, SK)</h1>
<p class="subtitle lead">Project report of Group C (WIP)</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Hongyue Kang </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            MSc Urbanism
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Kelly Schoonderwoerd </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            MSc Geomatics
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Viola Ebermannová </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            MSc Urbanism
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<!-- ## This is a computational notebook -->
<!-- This report was created using Quarto. To learn more about Quarto see <https://quarto.org>. -->
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p><strong><em>How to approach stream restoration so that it gives place for desired urban and community facilities, as well as improving native biodiversity, ecological connectivity, and water retention in the landscape?</em></strong></p>
<p>This report presents a spatial Multi Criteria Data Analysis and Typology Construction to determine possibilities for restoration of the Teplica river in the town Senica (Slovakia).</p>
<p>Note: This is student work created as part of the Applied Spatial Analysis for Sustainable Urban Development course at TU Delft.</p>
<section id="key-words" class="level5">
<h5 class="anchored" data-anchor-id="key-words">Key words:</h5>
<p>Urban Stream Restoration, Sustainability, Multi Criteria Decision Analysis, Typology Construction, K-means clustering, Senica, Slovakia</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/_SenicaOnTheEdgeOfTeplica_googleStreetview.png" class="img-fluid figure-img"></p>
<figcaption>River Senica on the edge of Teplica (Google Street View, 2012)</figcaption>
</figure>
</div>
</section>
<section id="colophon" class="level3">
<h3 class="anchored" data-anchor-id="colophon">Colophon</h3>
<section id="students-contact-roles-and-contributions" class="level4">
<h4 class="anchored" data-anchor-id="students-contact-roles-and-contributions">Students – contact, roles and contributions</h4>
<p>Hongyue Kang (MSc track Urbanism, BK TU Delft, hongyuekang@tudelft.nl) – Presentation Lead, Data Analyst (microclimate analysis, NDVI)</p>
<p>Kelly Schoonderwoerd (MSc Geomatics, BK TU Delft, K.R.Schoonderwoerd@student.tudelft.nl) – Data Analyst (surface temperature), R Expert, Clustering Lead</p>
<p>Viola Ebermannová (MSc track Urbanism, BK TU Delft, v.ebermannova@student.tudelft.nl) – Project Coordinator, Research Lead, Design Lead (graphic guidelines and layout templates), Data Analyst (analysis geometry construction, space syntax analysis), MCDA Lead</p>
</section>
<section id="course-information" class="level4">
<h4 class="anchored" data-anchor-id="course-information">Course information</h4>
<p>Created as part of the course: ARFW0501 Applied Spatial Analysis for Sustainable Urban Development (2024/25 Q4), Faculty of Architecture and the Built Environment.</p>
<p>Tutors: Dr.&nbsp;Daniele Cannatella, Dr.&nbsp;Claudiu Forgaci, Yehan Wu, PhD</p>
<p>In collaboration with the <a href="www.interreg-central.eu/projects/rebioclim/">ReBioClim</a> project.</p>
</section>
</section>
<section id="introduction-of-the-case-problem-statement-and-objectives" class="level3">
<h3 class="anchored" data-anchor-id="introduction-of-the-case-problem-statement-and-objectives">Introduction of the case, problem statement, and objectives</h3>
<p>Teplica is a small river flowing through the town of Senica, it is a tributary of the river Myjava in the Morava River basin (tributary of Danube, Black Sea drainage basin.) Senica lays in western Slovakia, it is a municipality with a slightly shrinking population of just under 20&nbsp;000 inhabitants. (Mesto Senica 2025)</p>
<p>The stream is now not integrated well into the urban fabric of Senica, often hidden in a jungle of high dense vegetation and flowing significantly lower than the surrounding area, acting as a barrier. This means the inhabitants cannot make use of the benefits an urban stream might bring to a town, such as improved recreation opportunities and communal and urban facilities benefiting from the location at the riverbank.</p>
<p>In a large portion of the stream, the riverbed was straightened and artificially reinforced. This leads to decreased water retention in the landscape, contributing to (soil) drought, and decreasing the cooling potential of the stream area. Moreover, it decreases the flood protection ability of the stream bed by not providing natural flood spillage areas, directing water directly downstream.</p>
<p>The stream corridor is an official biocorridor defined in the Slovakian Spatial System of Ecological Stability (ÚSES), a chain of ecosystems allowing for ecological flows. Right now, only the small footprint of the artificial banks is consistently covered by “natural” vegetation. This vegetation might technically be biodiverse, however the thin artificial riverbed leads to valuable natural floodplain ecosystems missing.</p>
<p><strong><em>How to approach stream restoration so that it gives place for desired urban and community facilities, as well as improving native biodiversity, ecological connectivity, and water retention in the landscape?</em></strong></p>
<p>This project is a spatial analysis of the stream flood plain highlighting the potentials for interventions targeting the topics of quality of life, biodiversity, and climate adaptation. It also proposes categorisation of spaces based on characteristics connected to the topics aiming at the simplification of visioning and design process of urban stream restoration interventions.</p>
</section>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<p>To determine the potentials for sustainable urban stream restoration interventions, we use Multi Criteria Decision Analysis. This analysis method offers an evidence-based evaluation of the suitability of area for intervention targeting different objectives based on predefined quantified criteria. (See chapter <a href="#mcda">MCDA</a>.)</p>
<p>To construct typologies of spaces based on biodiversity, quality of life, and climate adaptation characteristics we use k-means clustering. We use selected quantified criteria to discover patterns in how they combine in the flood plain area spaces. These typologies offer a simplified look at the area, being a good base for model examples of typical interventions. (See chapter <a href="#typology-construction">Typology construction</a>.)</p>
<p>For both approaches, we perform the analysis on morphologically defined spatial units, which were tailor-made for the flood plain of Teplica in the municipality of Senica. (See chapter <a href="#analysis-geometry">Analysis geometry</a>.)</p>
<p>The attributes/criteria we selected to represent the characteristics of spaces in the river flood plain are described in the chapter <a href="#selecting-objectives-and-criteria-three-pillar-system">Selecting objectives and criteria – three pillar system</a>. We used all these criteria for MCDA analysis, and chose four of them for the typology construction.</p>
<p>Spatial analysis was conducted and maps produced by <a href="https://qgis.org/">QGIS</a>, an open source GIS (Geographic Information System) software, including the <a href="https://smog.chalmers.se/projects/pst-plugin-for-qgis/">PST plugin</a> (SMOG n.d.). Typology construction was conducted through R scripts directly in the report file. Some data was accessed and analysed through Google Earth Engine.</p>
<section id="reproducibility-self-assessment" class="level3">
<h3 class="anchored" data-anchor-id="reproducibility-self-assessment">Reproducibility self assessment</h3>
<p>This reproducibility self assessment is based on the ReproducibilityChecklist.md file (in main directory).</p>
<p>Project documentation is up to the checklist standards (README files in subfolders could be more detailed). Data availability could be improved by separating raw and aggregated data and provided proper descriptions of file structure and attributes, as well as citation information. The data does use open formats (.gpkg). We used open software to conduct analyses, but some graphic work was done in paid graphic software. The version numbers of software should be listed (it is possible we did not used the same versions within the team.)</p>
<p>The workflow is documented quite clearly, although in some parts the reproducibility is limited (subjectively assigned criteria.) When using code, it is well documented in the report and modular. The project is structured in a single folder repository with a quite consistent naming structure. The project folder could be better structured into data, code, documentation, and results. The project is published as a github repository with a persistent identifier.</p>
<p>Overall, reproducibility is quite good, however it is lacking in some workflows and structure and description of provided data.</p>
</section>
</section>
<section id="mcda" class="level2">
<h2 class="anchored" data-anchor-id="mcda">MCDA</h2>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Multi Criteria Decision Analysis is a research approach that advises decision making based on evaluation of multiple objectives and criteria. It aims to formalize problems and evaluate them by mathematical means. <!-- Do we need a source? --></p>
</div>
</div>
</div>
<p>We use Multi Criteria Decision Analysis (MCDA) to determine suitability of areas in Teplica river floodplain in the city of Senica for urban stream restoration measures targeting specific themes, and also in general for sustainable urban stream restoration measures.</p>
<section id="explanation-of-how-mcda-works" class="level3">
<h3 class="anchored" data-anchor-id="explanation-of-how-mcda-works">Explanation of how MCDA works</h3>
<p>This is a short overview of how Multi Criteria Decision Analysis works in this research project. MCDA starts with a research question and subquestions, leading to objectives. Our research objectives are described further in the report (see chapter <a href="#selecting-objectives-and-criteria-three-pillar-system">Selecting objectives and criteria – three pillar system</a>). From these, we determined criteria that will be used to describe/answer them.</p>
<p>We determined the mutual importance of the attributes and assigned weights to them based on pairwise comparison. For this, we used a Saaty matrix. In the Saaty matrix, in each cell we stated how many times we think the criterion in the row is more important than the criterion in the column. To evaluate the Saaty matrix, a sum is calculated for each row. These values are normalised to determine the weights, so the sum of the weights is 1. An example is shown in the figure below in the “weight determination”, and our approach is explained further in a dedicated chapter (<a href="#weighting">Weighting</a>).</p>
<p>We divided the area around Teplica river in Senica into spatial units that form our analysis geometry, the workflow is described in a dedicated chapter (<a href="#analysis-geometry">Analysis geometry</a>). These are the units on which the research questions will be answered. For each of these units, we determined the value of each criterion. We normalised these criteria to 0-1, so they are comparable with each other.</p>
<p>Then, we multiplied the criteria by the weights to get their relative value (for each spatial unit, the sum of all the weighted criteria falls into interval 0-1). We determined the result of MCDA for the main research question, as well as for individual subquestions.</p>
<p>You can see a simplified example demonstrating the principles of MCDA in the figure below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/MCDA_explanation.png" class="img-fluid figure-img"></p>
<figcaption>Diagram of how MCDA works, with a simplified example of analysis geometry and criteria (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
<section id="selecting-objectives-and-criteria-three-pillar-system" class="level3">
<h3 class="anchored" data-anchor-id="selecting-objectives-and-criteria-three-pillar-system">Selecting objectives and criteria – three pillar system</h3>
<p>ReBioClim is a project focused on sustainable urban stream restoration, and it builds on three pillars: <em>“The primary aim is to improve the quality of life in cities and at the same time to promote biodiversity and climate adaptation.”</em> (ReBioClim n.d.)</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDA_venndiagram.png" class="img-fluid figure-img" width="400"></p>
<figcaption>Approach: combining the themes of biodiversity, climate adaptation, and quality of life (by Viola Ebermannová)</figcaption>
</figure>
</div>
<p>These three themes form the three branches of our MCDA research tree. In each of these branches, we chose a number of sub-themes to determine the suitability of different more specific types of interventions. These sub-themes consist of attributes which we aggregate to use for MCDA. MCDA is performed for each of the three themes, as well as for sustainable urban stream restoration as a whole. Each attribute was given a unique code to be used across our research for clarity.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDAresearchStructure_overview.png" class="img-fluid figure-img"></p>
<figcaption>Research structure – simplified flow chart of indicators used in each of the three themes (by Viola Ebermannová)</figcaption>
</figure>
</div>
<section id="detailed-research-structure" class="level4">
<h4 class="anchored" data-anchor-id="detailed-research-structure">Detailed research structure</h4>
<p>Each of the sub/themes comes with its own research subquestion. In the scheme below, you can see a more detailed look at the MCDA research structure, together with an overview of what data we use to evaluate the attributes, and what format of geometry that data is. More specifics of how we sourced the data, what it represents, and how we worked with it are described below in the Data Structure, and more in detail in the chapters dedicated to individual attributes.</p>
<iframe src="pdf/MCDA_researchStructure_detailed.pdf" width="100%" height="500" frameborder="0">
</iframe>
</section>
</section>
<section id="weighting" class="level3">
<h3 class="anchored" data-anchor-id="weighting">Weighting</h3>
<p>In MCDA, each attribute results in a quantifiable criterion. These criteria are normalised and weighed among each other based on their hierarchy of importance in relation to the research question. There are different approaches to determined the weights, we used pairwise comparison Saaty matrix. For this, we used <a href="https://fuzzyahp.holecekp.eu/en/info">Fuzzy AHP</a> by Pavel Holeček (Holeček n.d.).</p>
<p>We determined how many times more or less important is each criterion in relation to every other criterion. This was done in a subjective way, based on our understanding of the problem. The complete matrix of the importance ratios looks like this:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/CompleteSaatyMatrix.png" class="img-fluid figure-img"></p>
<figcaption>Complete Saaty Matrix. The meaning of the numbers is: “How many times more important is the criterion in the row compared to the criterion in the column?” (screenshot from <a href="https://fuzzyahp.holecekp.eu/en/">Fuzzy AHP</a> (Holeček n.d.))</figcaption>
</figure>
</div>
<p>For the matrix above, the weights were assigned as follows. Overall, highest weights were assigned to CA1temp (targeting cooling down summer surface temperature) and QL2acg (potential for central urban functions) and QL3gr (need of built up area for green). Criteria that scored high directly influence livability and offer a very actionable basis for the public sector and show potential for feasible and tenable investments.</p>
<table class="caption-top table">
<caption>Weights of MCDA criteria</caption>
<thead>
<tr class="header">
<th>Criterion</th>
<th>Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>B1uses</td>
<td>0.058</td>
</tr>
<tr class="even">
<td>B2pot</td>
<td>0.027</td>
</tr>
<tr class="odd">
<td>B3ndvi</td>
<td>0.083</td>
</tr>
<tr class="even">
<td>CA1temp</td>
<td>0.198</td>
</tr>
<tr class="odd">
<td>CA2soil</td>
<td>0.03</td>
</tr>
<tr class="even">
<td>QL1acl</td>
<td>0.098</td>
</tr>
<tr class="odd">
<td>QL2acg</td>
<td>0.235</td>
</tr>
<tr class="even">
<td>QL3gr</td>
<td>0.27</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/MCDA_weightsgraph.png" class="img-fluid figure-img"></p>
<figcaption>Graph of criteria weights (screenshot from <a href="https://fuzzyahp.holecekp.eu/en/">Fuzzy AHP</a> (Holeček n.d.))</figcaption>
</figure>
</div>
<p>Consistency is acceptable with consistency ratio CR = 0,086 (this is a mechanism to check if the manual assigning of importance ratios was consistent across the matrix):</p>
<div class="line-block">λmax = 8.847<br>
CI = 0.121<br>
RI = 1.4<br>
CR = 0.086</div>
</section>
<section id="analysis-geometry" class="level3">
<h3 class="anchored" data-anchor-id="analysis-geometry">Analysis geometry</h3>
<p>The values of MCDA criteria are evaluated on analysis geometry spatial units. We decided for creating a custom analysis geometry vector polygon layer consisting of morphologicaly determined spatial units. The decision to create geometry tailored to the local spatial conditions has two main reasons:</p>
<ol type="1">
<li>to make the analysis more accessible to locals,
<ul>
<li>by using familiar analysis geometry units (spatial units respecting recognisable urban and landscape linear orientation structures and long lines (streams, roads), completed by familiar grid structures (street structure, building blocks, boundaries of park areas and fields)</li>
<li>maps will be more intuitive to read, making the research more accessible and interpretation easier</li>
</ul></li>
<li>to make the results more actionable.
<ul>
<li>by analysing on logical spatial units</li>
<li>more space-specific results will make the analysis-intention-decision path shorter</li>
</ul></li>
</ol>
<p>The geometry was created mainly manually following four principles, in this order. It follows the structure of the <em>Regional biocorridor</em> as defined in <em>Spatial Ecological Stability System</em> (<em>ÚSES</em>) as a spine along the river Teplica. The bounds of the geometry were defined based on the flood plain of the river Teplica, as that is the area we consider “belongs” to the river. We followed morphological characteristics of the space to create smaller units. In case the units needed to be partitioned further, and morphology was not used, the partitioning was inspired by the parcel system. Each of these four principles will be explained in a dedicated section.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/analysisgeometry_overview.png" class="img-fluid figure-img"></p>
<figcaption>Four principles of determining analysis geometry units. (by Viola Ebermannová)</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/AnalysisGeometry.png" class="img-fluid figure-img"></p>
<figcaption>Overview of analysis geometry (by Viola Ebermannová)</figcaption>
</figure>
</div>
<section id="principle-1-úses" class="level5">
<h5 class="anchored" data-anchor-id="principle-1-úses">Principle 1: ÚSES</h5>
<p>At the spine of the analysis geometry is a <em>Regional biocorridor</em> as defined in <em>Spatial Ecological Stability System</em> (<em>ÚSES</em>) – an approximately 20 meter buffer around the Teplica stream. This is not a geometry created by us, it is directly taken from <a href="https://www.sazp.sk/zivotne-prostredie/starostlivost-o-krajinu/zelena-infrastruktura/dokumenty-uses-v-sr">official ÚSES map layer by SAŽP</a> (Slovak Environment Agency), 2023. We differentiate left and right bank, because it matters for accessibility (significant for all attributes in quality of life). In our opinion, apart from being an official spatial unit anchored in the binding spatial plans as having ecological priority, 20 m buffer is an accurate distance for the immediate surroundings of the river, (potentially) connected to it visually and audibly.</p>
<p>Workflow steps:</p>
<ol type="1">
<li><p>Retrieve data from <a href="https://www.sazp.sk/zivotne-prostredie/starostlivost-o-krajinu/zelena-infrastruktura/dokumenty-uses-v-sr">ÚSES</a>.</p></li>
<li><p>Isolate geometry of biocorridor along the stream Teplica, clip to a size slightly larger than municipality borders, divide dissolved corridor polygon into left and right bank using a the stream line from OSM waterway dataset.</p></li>
<li><p>Create temporary 40 m segments along the corridor (40 m was chosen because it partitions the ~40 m wide biocorridor into “squares”, and also as a good distance for having a more detailed analysis of the immediate stream surroundings.)</p>
<ul>
<li>This was done by constructing normals (length larger than corridor width) along the isolated river teplica line (from OSM waterway dataset) at 40 m intervals, manually adjusting the lines in areas where the normals intersected within the corridor (manually deleting and adding lines so the geometry seems “regular”), and splitting the corridor with these lines</li>
</ul></li>
<li><p>After executing steps 1-3 of the ÚSES principle, the other three principles were followed. In the end, Land Cover categories were manually assigned to all spatial units (see <a href="#land-cover-classification">Land cover classification</a> chapter). After this, the decision was made to merge some adjacent tiles into larger units to unify the level of detail with the rest of the spatial units and follow a similar morphological principle. This makes the results better comparable and helps the analysis be cohesive. Merging was done following these principles:</p>
<ul>
<li><p>units lay on the same riverbank (left/right),</p></li>
<li><p>units have the same land cover classification,</p></li>
<li><p>aim is to maintain division line continuity between the inner spine and the outer floodplain (see following principles for explanation of what this is.)</p></li>
</ul></li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/analysisgeometry_uses.png" class="img-fluid figure-img"></p>
<figcaption>Biocorridor at the core of the geometry as the immediate banks of the river. (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
<section id="principle-2-flood-plain" class="level5">
<h5 class="anchored" data-anchor-id="principle-2-flood-plain">Principle 2: Flood plain</h5>
<p>The bounds of the analysis geometry were determined based on the floodplain of the river indicated by flood danger maps. This is the area that “belongs” to the river, thus it should be restored together with the watercourse.</p>
<p>Workflow:</p>
<ol type="1">
<li><p>Find flood danger (<em>Povodňové ohrozenie</em>) data, this project uses map accessible through <a href="https://mpt.svp.sk/svp_vmapportal/?basemap=orto2023&amp;zoom=5&amp;lat=48.683285&amp;lng=17.339609">SVP š.p. map viewer</a> (SVP š.p. 2023). (The outline was based on raster data available in an online map viewer. In case of raster or vector data being available directly as a retrievable GIS layer, it would be beneficial to use a more exact boundary.)</p></li>
<li><p>Trace the flood danger area related to Teplica stream (discarding flood areas of other streams), following morphological boundaries (morphological boundaries already largely follow the approximate flood plain boundary).</p></li>
<li><p>This results in an “outer boundary” polygon of the (approximate) flood plain.</p></li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/analysisgeometry_flood.png" class="img-fluid figure-img"></p>
<figcaption>Flood plain - area belonging to the river should be treated as a whole. (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
<section id="principle-3-morphology" class="level5">
<h5 class="anchored" data-anchor-id="principle-3-morphology">Principle 3: Morphology</h5>
<p>The flood plain was manually partitioned based on local morphology and land cover, as analysed from Bing aerial photos. (Bing Aerial View 2018)</p>
<p>Workflow</p>
<ol type="1">
<li><p>Retrieve aerial imagery of area (we used Bing Aerial View, 2018).</p></li>
<li><p>Analyse morphology of area, identify important orientation lines (roads through landscape or important roads/other linear elements in urban fabric, streams, important paths in landscape), identify grid structures and recognisable planar elements present in the area (street structure, building blocks, park and field boundaries)</p></li>
<li><p>Draw by lines the morphology:</p>
<ul>
<li><p>linear elements of sufficient width (at minimum ~ 15 m): by drawing edge boundaries, divide into segments based on spatial structure (changing surrounding land cover, morphology), if the spatial structure is consistent, create arbitrary segments of 100-200 m length.</p></li>
<li><p>all other important linear elements (of not sufficient width): by drawing the center line</p></li>
<li><p>planar elements and grid structures: fill up the remaining space by drawing a grid following the structure of the fabric of the landscape or urban fabric, with cell size approximately 50-200 m large. The cell size depends on the grain size of the morphology (i.e.&nbsp;a farm house in the middle of large fields will have a smaller cell than the grid size of the surrounding agricultural land)</p></li>
<li><p>This is a subjective principle, and really depends on agency of the researcher.</p></li>
</ul></li>
<li><p>Split the “outer boundary” polygon of the (approximate) flood plain by the lines produced in step 3 (leaving the separation of the spine/ÚSES biocorridor intact.)</p></li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/analysisgeometry_space.png" class="img-fluid figure-img"></p>
<figcaption>Polygons are based on morphology. (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
<section id="principle-4-parcelation" class="level5">
<h5 class="anchored" data-anchor-id="principle-4-parcelation">Principle 4: Parcelation</h5>
<p>In some cases, division of spatial units produces units that we consider too large. In these cases, the larger spatial units determined morphologically are further split in a way inspired by the parcelation structure to create a smaller grain. This typically happens in areas with large unpartitioned agricultural fields. Although this is not a very intuitive/recognisable division, as these boundaries are often not visible in the landscape, they form the basis of ownership and therefore influence the possible interventions.</p>
<p>Workflow:</p>
<ol type="1">
<li><p>Retrieve cadaster data, we used data from <a href="https://kataster.skgeodesy.sk/eskn/rest/services/">ArcGIS Rest service of the Portal for Electronin Services of the Cadaster</a> of Slovakia (ÚGKK SR, n.d.).</p></li>
<li><p>For spatial units formed by previous steps, that are larger than approximately ~ 150-200 m, create additional divisions inspired by the cadaster parcelation.</p>
<ul>
<li><p>Not following all boundaries, but creating regular partitioning of the larger units with grid size of approximately 80-120 m.</p></li>
<li><p>Preferably, there is a continuity of separation lines between larger floodplain and the inner spine division.</p></li>
</ul></li>
<li><p>This results in analysis geometry with a sufficiently uniform grain size based in actual spatial structure.</p></li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/analysisgeometry_parcelation.png" class="img-fluid figure-img"></p>
<figcaption>Some larger uniform areas were partitioned based on parcelation. (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
<section id="land-cover-classification" class="level4">
<h4 class="anchored" data-anchor-id="land-cover-classification">Land cover classification</h4>
<p>The analysis geometry was manually assigned Land Cover classes. Below is an overview of these classes with a typical example. Each land cover class was assigned an estimate ecological quality indicator based on intuition.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/LandCover.png" class="img-fluid figure-img"></p>
<figcaption>Landcover overview (by Viola Ebermannová)</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/LandCover_typology.png" class="img-fluid figure-img"></p>
<figcaption>Typical examples of land cover classes, draft estimate ecological quality indicator (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="data-structure" class="level3">
<h3 class="anchored" data-anchor-id="data-structure">Data structure</h3>
<p>This is an overview of data formats and sources used, as well as a simplified description on how original geometry formats were aggregated onto our vector polygon analysis geometry spatial units. More detailed descriptions can be found in the attribute sub chapters of this report.</p>
<p>General workflow for all of the attributes was:</p>
<ol type="1">
<li><p>Perform calculations and create base layer</p></li>
<li><p>Normalise values</p></li>
<li><p>Aggregate</p></li>
<li><p>Normalise again</p></li>
</ol>
<p>We used linear min-max normalisation to 0-1, eventually inversed (1-[standard min-max normalisation]).</p>
<iframe src="pdf/MCDA_DataStructure.pdf" width="100%" height="500" frameborder="0">
</iframe>
</section>
<section id="biodiversity" class="level3">
<h3 class="anchored" data-anchor-id="biodiversity">Biodiversity</h3>
<p><strong>How to improve local and supra local biodiversity resilience by interventions within the stream flood plain?</strong> -&gt; Which spaces to prioritize based on ecological value and&nbsp;feasibility of intervention?</p>
<p>In this chapter, we analyse the suitability of analysis geometry spatial units for interventions targeting biodiversity objectives. The examined characteristics are:</p>
<ul>
<li><p>Connectivity to the official Slovakian Spatial system of ecological stability (ÚSES) –&gt; prioritise interventions in areas that are a part of, or well connected to, the ecological stability system.</p></li>
<li><p>Improvement potential and feasibility of intervention –&gt; prioritise interventions in areas where the feasibility of investment is high and that have a mediocre ecological quality offering potential for (easy) significant improvement.</p></li>
<li><p>Current state of vegetation –&gt; prioritise interventions in areas where the state of vegetation determined by NDVI (Normalised Difference Vegetation Index) is low.</p></li>
</ul>
<section id="b1uses-which-spaces-should-be-prioritised-because-of-their-connectivity-to-úses" class="level4">
<h4 class="anchored" data-anchor-id="b1uses-which-spaces-should-be-prioritised-because-of-their-connectivity-to-úses"><em>B1uses</em> – Which spaces should be prioritised because of their connectivity to ÚSES?</h4>
<section id="data" class="level5">
<h5 class="anchored" data-anchor-id="data">Data</h5>
<section id="what-is-úses" class="level6">
<h6 class="anchored" data-anchor-id="what-is-úses">What is ÚSES?</h6>
<p>Územný systém ekologickej stability (ÚSES) (Spatial system of ecological stability) is a system of spatial units intended to securing the ecological stability of Slovakian landscape, connecting natural areas, and protection of biotopes and representative species in their natural habitats. It is a legally anchored documentation (Act No.&nbsp;543/2002 Z. z. – About the protection of nature and landscape).</p>
<p>The elements of ÚSES are biocenters, biocorridors (connecting biocenters to allow for movement of organisms and genetical information exchange), and interaction elements (spatially tied with biocorridors). These elements are defined on supraregional, regional, and local scale.</p>
<p>(<a href="https://www.sazp.sk/zivotne-prostredie/starostlivost-o-krajinu/zelena-infrastruktura/uzemny-system-ekologickej-stability-uses">SAŽP n.d.</a>)</p>
</section>
<section id="úses-in-senica" class="level6">
<h6 class="anchored" data-anchor-id="úses-in-senica">ÚSES in Senica</h6>
<p>In Senica, there is a regional biocorridor along the river Teplica, and a larger supraregional biocorridor on the south-east side of the city. For the purposes of our analysis, we consider them of the same importance.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/B1uses.png" class="img-fluid figure-img"></p>
<figcaption>Map of ÚSES within our area (by Hongyue Kang)</figcaption>
</figure>
</div>
</section>
</section>
<section id="aggregation-and-normalisation" class="level5">
<h5 class="anchored" data-anchor-id="aggregation-and-normalisation">Aggregation and normalisation</h5>
<p>Values were assigned based on the level of connectivity to ÚSES. Highest value was assigned to polygons intersecting with ÚSES elements, polygons that are connected by continuous green land cover (as defined in Land Cover general type of landcover) were also assigned a slight priority.</p>
<div class="line-block">polygons in which ÚSES elements are present –&gt; 1<br>
polygons that are connected by (contuinuos) “green” land cover to ÚSES elements –&gt; 0,3<br>
other polygons –&gt; 0</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDA_conclusions_B1uses.png" class="img-fluid figure-img"></p>
<figcaption>Criterion B1uses – Connectivity to ÚSES (normalised.) (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="b2pot-which-spaces-should-be-prioritised-based-on-ecological-quality-improvement-potential-and-feasibility-of-intervention" class="level4">
<h4 class="anchored" data-anchor-id="b2pot-which-spaces-should-be-prioritised-based-on-ecological-quality-improvement-potential-and-feasibility-of-intervention"><em>B2pot</em> – Which spaces should be prioritised based on ecological quality improvement potential and feasibility of intervention?</h4>
<section id="data-1" class="level5">
<h5 class="anchored" data-anchor-id="data-1">Data</h5>
<p>Improvement potential indicator is determined for each lands cover typology (See chapter <a href="#land-cover-classification">Land cover classification</a>) based on high impact improvement potential and good investment feasibility. Our argument is that spaces with a potential for a high impact improvement and at the same time good investment feasibility should be prioritised, because of good actionability of intentions/plans.</p>
<p>Potential for high impact improvement is determined by unsatisfactory ecological quality. Investment feasibility is determined by attractivity to invest in biodiversity improvement and in general spatial quality improvement in an area like this. High investment feasibility is in the surrounding of dwellings, in spaces that are already upkept. Low investment feasibility is in agricultural areas, where produce is prioritised. In these areas in general it is advised to use agricultural methods that can aid local biodiversity.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/B_LandCover_ImprovementPotential.png" class="img-fluid figure-img"></p>
<figcaption>Ecological quality improvement potential in bottom row. (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
<section id="aggregation-and-normalisation-1" class="level5">
<h5 class="anchored" data-anchor-id="aggregation-and-normalisation-1">Aggregation and normalisation</h5>
<p>The potential was calculated on range 0-1 directly on Analysis geometry polygons.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDA_conclusions_B2pot.png" class="img-fluid figure-img"></p>
<figcaption>Criterion B2pot – Improvement potential (normalised.) (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="b3ndvi-which-spaces-should-be-prioritized-based-on-current-state-of-the-vegetation" class="level4">
<h4 class="anchored" data-anchor-id="b3ndvi-which-spaces-should-be-prioritized-based-on-current-state-of-the-vegetation"><em>B3ndvi</em> – Which spaces should be prioritized based on current state of the vegetation?</h4>
<section id="data-2" class="level5">
<h5 class="anchored" data-anchor-id="data-2">Data</h5>
<section id="what-is-ndvi" class="level6">
<h6 class="anchored" data-anchor-id="what-is-ndvi">What is NDVI?</h6>
<p>Normalised Difference Vegetation Index (NDVI) is an index <em>“used to quantify vegetation greenness and is useful in understanding vegetation density and assessing changes in plant health.”</em> (USGS n.d.)</p>
</section>
<section id="calculating-ndvi" class="level6">
<h6 class="anchored" data-anchor-id="calculating-ndvi">Calculating NDVI</h6>
<p>The steps we take to calculate the NDVI are as follow:</p>
<ol type="1">
<li><p>Sentinel-2 satellite imagery was accessed via Google Earth Engine (GEE), covering the study area during the growing season to ensure accurate vegetation representation.</p></li>
<li><p>The Normalized Difference Vegetation Index (NDVI) was calculated within GEE using the standard formula: NDVI=(B8-B4)/(B8+B4) where B8 represents the near-infrared (NIR) band and B4 represents the red band. The resulting NDVI raster was exported from GEE as a GeoTIFF file and imported into QGIS.</p></li>
<li><p>In QGIS, the NDVI layer was reprojected, clipped to the study boundary, and further analyzed using raster statistics and classification to evaluate vegetation cover across different spatial units along the Teplica River.</p></li>
</ol>
<p>Based on the different value of NDVI mean, we can deduce the vegetation state in each spatial geometry.</p>
<div class="line-block"><strong>&lt; 0</strong> – Water bodies, shadows, or noise<br>
<strong>0–0.1</strong> – Bare soil or urban hardscape<br>
<strong>0.1–0.3</strong> – Sparse or dry vegetation<br>
<strong>0.3–0.6</strong> – Moderate vegetation<br>
<strong>&gt; 0.6</strong> – Dense and healthy vegetation</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/B3ndvi.png" class="img-fluid figure-img"></p>
<figcaption>NDVI classification (by Hongyue Kang)</figcaption>
</figure>
</div>
</section>
</section>
<section id="aggregation-and-normalisation-2" class="level5">
<h5 class="anchored" data-anchor-id="aggregation-and-normalisation-2">Aggregation and normalisation</h5>
<p>Data was aggregated based on average value within analysis geometry polygon, and normalised by 1-[linear min-max] –&gt; priority is given to low quality vegetation.</p>
<p>Note: In the area, there is a large water body present. This water body was assigned a high value for the nornalised <em>B3ndvi</em>, because water has a low NDVI value. That means it is classified as area with a large priority to improve the green cover based on its current state, despite there being no actual green cover. This makes the analysis biased.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDA_conclusions_B3ndvi.png" class="img-fluid figure-img"></p>
<figcaption>Criterion B3ndvi – Current state of vegetation (normalised.) (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="weighting-1" class="level4">
<h4 class="anchored" data-anchor-id="weighting-1">Weighting</h4>
<p>An overall pairwise comparison matrix was created for all indicators at once (see <a href="#weighting">Weighting</a>). For comparing biodiversity criteria among each other, the values were given as follows:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/B_SaatyMatrix.png" class="img-fluid figure-img"></p>
<figcaption>Partial pairwise comparison matrix – biodiversity (screenshot from <a href="https://fuzzyahp.holecekp.eu/en/">Fuzzy AHP</a> (Holeček n.d.))</figcaption>
</figure>
</div>
<p>The calculated weights for biodiversity indicators are:</p>
<table class="caption-top table">
<caption>Weights of biodiversity criteria</caption>
<thead>
<tr class="header">
<th>Criterion</th>
<th>Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>B1uses</td>
<td>0.058</td>
</tr>
<tr class="even">
<td>B2pot</td>
<td>0.027</td>
</tr>
<tr class="odd">
<td>B3ndvi</td>
<td>0.083</td>
</tr>
</tbody>
</table>
</section>
<section id="biodiversity-conclusion" class="level4">
<h4 class="anchored" data-anchor-id="biodiversity-conclusion">Biodiversity conclusion</h4>
<p>In this part, we developed a spatially explicit composite biodiversity index map for the spatial geometry by weighting three criteria: <em>B1uses</em> (connectivity to ÚSES – Slovakian official Spatial system of ecological stability), <em>B2pot</em> (ecological quality improvement and feasibility, potential), and <em>B3ndvi</em> (current state of vegetation based on NDVI). Because we agree that vegetative cover remains a dominant factor influencing riparian biodiversity, in line with existing ecological connection, we assigned <em>B3ndvi</em> with the highest weight (0.083), followed by <em>B1uses</em> (0.058) and <em>B2pot</em> (0.027).</p>
<p>The conclusion map resembles the <em>B3ndvi</em> map a lot, with the addition of the ÚSES biocorridor(s) as higher priority. The two most important criteria, <em>B3ndvi</em> and B1uses are in a way contradictory: in ÚSES areas, it is more likely that the green has a high NDVI and therefore low <em>B3ndvi</em> value. However, in B1uses, spaces that are not green are also considered connected if they are adjacent to a green space continuously connected to ÚSES. Moreover, the supraregional biocorridor at the eastern edge of the city does not necessarily have high NDVI, as it is a larger structure.</p>
<p>In general, the highest scores are in the east of the town, where the supraregional corridor passes the town, <em>B2pot</em> is the highest, and because of it being an urban area, NDVI is quite low -&gt; <em>B3ndvi</em> is quite high. <strong>Overall, the highest suitability for biodiversity-oriented interventions seems to be in neglected urban or industrial areas, and especially clearly in urban areas of suburban character in the east of the town.</strong> High values are also present in the water area at the north of the analysis area, however, we suspect that to be a mistake caused by improper use of NDVI data: for water, NDVI is very low, so the score of <em>B3ndvi</em> is very high, which is misleading.</p>
<p>We recommend improving native biodiversity by implementing low maintenance nature-like native biotope landscaping in industrial areas. We also recommend improving biodiversity in the streets of the town with targeted interventions. In general, it is also beneficial to transform uniform fields to include dense vegetation patches that improve the resilience of local ecosystems and in general support biodiversity.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDA_conclusions_B.png" class="img-fluid figure-img"></p>
<figcaption>MCDA Biodiversity conclusion (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="climate-adaptation" class="level3">
<h3 class="anchored" data-anchor-id="climate-adaptation">Climate adaptation</h3>
<p><strong>How to use areas in the flood plain to capture water in the landscape?</strong> -&gt; Where is good space for infiltration basins and natural flood protection measures based on soil types, and where is space for (wet) cooling measures?</p>
<p>In this chapter, we analyse the suitability of analysis geometry spatial units for interventions targeting climate adaptation objectives. The examined characteristics are:</p>
<ul>
<li><p>Land surface temperature –&gt; prioritise (wet) cooling measures in areas with a high summer surface temperature.</p></li>
<li><p>Soil retention ability and permeability –&gt; prioritise interventions targeting landscape water retention capacity in areas where the retention ability and permeability high.</p></li>
</ul>
<p>We focus on landscape water retention a lot, because in western Slovakia, high summer soil drought is a pressing problem. (Intersucho 2025) In sustainable stream restoration, measures should be taken to combat this large scale problem by taking small steps across the landscape.</p>
<section id="ca1temp-which-spaces-should-be-prioritized-for-interventions-aimed-at-cooling-the-area-down" class="level4">
<h4 class="anchored" data-anchor-id="ca1temp-which-spaces-should-be-prioritized-for-interventions-aimed-at-cooling-the-area-down"><em>CA1temp</em> – Which spaces should be prioritized for interventions aimed at cooling the area down?</h4>
<section id="data-3" class="level5">
<h5 class="anchored" data-anchor-id="data-3">Data</h5>
<section id="land-surface-temperature" class="level6">
<h6 class="anchored" data-anchor-id="land-surface-temperature">Land Surface Temperature</h6>
<p>To estimate the need for cooling measures, we use Land Surface Temperature (LST) during a 3 month summer period.</p>
</section>
<section id="calculating-lst" class="level6">
<h6 class="anchored" data-anchor-id="calculating-lst">Calculating LST</h6>
<p>To analyse surface temperatures, we found a <a href="https://code.earthengine.google.com/ac986028b56a794aefd3ea54e9cb09ba">Google Earth Engine script</a> made by <a href="https://www.youtube.com/watch?v=3LOMNzBHmjs">Ramadhan</a> on YouTube (2024) that uses information from Sentinel-2, LANDSAT, and DEM to predict a raster LST (land surface temperature) with a higher resolution than other available datasets on LST, namely 10-meter resolution. The computations are complicated and will only be discussed in general lines in this report, but the results are relevant and useful to our research. Mainly to answer the question of which spaces should be prioritized to be wetter to help the area cool down, because now it is too hot. The draft image shows the results for dates 2024-06-01 to 2024-08-31, since these three months include the summer and will therefore be most susceptible for heat stress, which makes this time period interesting to look at for our research.</p>
<p>The method uses the different datasets to extract several attributes (e.g.&nbsp;B2, B3, elevation, slope, wetness, greenness, dryness, etc.). Together with the recorded LST data, a correlation between attributes and LST is calculated. For the six attributes with the highest correlation, the average correlation matrices are computed and the three lowest correlation matrices are used to set up a model. The model is then trained with test data to predict LST based on the provided correlation information. Then, the model is applied to data in the area of interest to create a dataset with LST predictions that covers the full area in detail (instead of the available recorded LST datasets with big gridcells).</p>
<p>The Google Earth Engine (GEE) script was adapted to analyse our area of interest (Senica and surroundings) and an interesting time period as mentioned earlier. The code produced a GeoTiff file that we downloaded for further processing. The LST values in this file are given in degrees Celsius and range from 27-38. The raster GeoTiff file was combined with our analysis geometry layer using the ‘zonal statistics’ tool in QGIS. This resulted in a vector layer with our analysis polygons, including a column in the attribute table representing the mean value of the LST raster layer inside that specific polygon. This value represents the aggregation of LST values, which was then normalized with the following statement in the field calculator:</p>
<pre><code>1 - (maximum("_mean") - "_mean") / (maximum("_mean") -  minimum("_mean"))</code></pre>
<p>The normalization is a linear min-max normalization for a benefit criterion, meaning that areas with a higher LST should be prioritized for improvements and development. A lower LST would be desirable and thus has less need for spatial developments to improve LST, which is represented in lower normalization values (closer to 0).</p>
<!-- General steps (DRAFT):

* Use GEE code (reference properly) 
* Download GeoTiff 
* Use zonal statistics
* Combine raster layer with combined polygons using zonal statistics tool 
* This results in onder andere the mean column 
* Use mean (aggregation) to normalise: (maximum("_mean") - "_mean") / (maximum("_mean") -  minimum("_mean"))
* The lower the LST, the better and thus the higher norm value (closer to 1 for lower LST) 
* Clean up and rename, save as separate file for further processing -->
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/CA1temp_LST_map02.png" class="img-fluid figure-img"></p>
<figcaption>Map of predicted LST values (by Kelly Schoonderwoerd)</figcaption>
</figure>
</div>
</section>
</section>
<section id="weigting-and-normalisation" class="level5">
<h5 class="anchored" data-anchor-id="weigting-and-normalisation">Weigting and normalisation</h5>
<p>Weighted as mean by Zonal statistics tool (QGIS).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDA_conclusions_CA1temp.png" class="img-fluid figure-img"></p>
<figcaption>Criterion CA1temp – need for cooling (normalised.) (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="ca2soil-where-does-the-soil-have-high-potential-for-water-retention" class="level4">
<h4 class="anchored" data-anchor-id="ca2soil-where-does-the-soil-have-high-potential-for-water-retention"><em>CA2soil</em> – Where does the soil have high potential for water retention?</h4>
<section id="data-4" class="level5">
<h5 class="anchored" data-anchor-id="data-4">Data</h5>
<section id="soil-retention-ability-and-permeability" class="level6">
<h6 class="anchored" data-anchor-id="soil-retention-ability-and-permeability">Soil retention ability and permeability</h6>
<p>To determine suitability for water retention measures in the landscape, we use data about Soil retention ability and permeability. Soil retention ability in this map means the ability of soil to capture and retain water. It can contribute to limiting desertification and prevent flood. Permeability describes the ease with which the soil to let water, air, and other substances move through. In high permeability soil, water can be quickly redirected from the surface into the soil mass.</p>
<p>Apart from acting as climate adaptation by combating drought and flood, improving landscape water retention has direct positive impact on soil quality and fertility, also through decreasing the water erosion danger. (Agrointeg n.d.) (Suchá 2021) (Šachová 2010)</p>
</section>
<section id="soil-characteristics-in-senica" class="level6">
<h6 class="anchored" data-anchor-id="soil-characteristics-in-senica">Soil characteristics in Senica</h6>
<p>In Senica, there are two different combinations of retention ability and permeability:</p>
<ol type="1">
<li><p>High retention ability and medium permeability – relatively more suitable for landscape water retention measures</p></li>
<li><p>Medium retention ability and medium permeability – relatively less suitable for landscape water retention measures</p></li>
</ol>
<p>Note: This data from From Atlas of Slovakia (SAŽP 2002-2024) is quite small scale. It would be beneficial to acquire more detailed data of the soil surface layers.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/CA2soil.png" class="img-fluid figure-img"></p>
<figcaption>Soil potential (by Hongyue Kang)</figcaption>
</figure>
</div>
</section>
</section>
<section id="aggregation-and-normalisation-3" class="level5">
<h5 class="anchored" data-anchor-id="aggregation-and-normalisation-3">Aggregation and normalisation</h5>
<p>Values were assigned based on the soil characteristic on the majority of the spatial unit area.</p>
<div class="line-block">RS Medium+ P Medium -&gt; 0,5<br>
RS High+ P Medium -&gt; 1</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDA_conclusions_CA2soil.png" class="img-fluid figure-img"></p>
<figcaption>Criterion CA2soil – Retention ability (normalised.) (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="weighting-2" class="level4">
<h4 class="anchored" data-anchor-id="weighting-2">Weighting</h4>
<p>An overall pairwise comparison matrix was created for all indicators at once (see <a href="#weighting">Weighting</a>). For comparing climate adaptation criteria among each other, the values were given as follows:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/CA_SaatyMatrix.png" class="img-fluid figure-img"></p>
<figcaption>Partial pairwise comparison matrix – climate adaptation(screenshot from <a href="https://fuzzyahp.holecekp.eu/en/">Fuzzy AHP</a> (Holeček n.d.))</figcaption>
</figure>
</div>
<p>The calculated weights for climate adaptation criteria are:</p>
<table class="caption-top table">
<caption>Weights of climate adaptation criteria</caption>
<thead>
<tr class="header">
<th>Criterion</th>
<th>Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CA1temp</td>
<td>0.198</td>
</tr>
<tr class="even">
<td>CA2soil</td>
<td>0.03</td>
</tr>
</tbody>
</table>
</section>
<section id="climate-adaptation-conclusion" class="level4">
<h4 class="anchored" data-anchor-id="climate-adaptation-conclusion">Climate adaptation conclusion</h4>
<p>For climate adaptation, we considered two key factors: land surface temperature (<em>CA1temp</em>) and water retention capacity (<em>CA2soil</em>). For urban stream restoration climate adaptation measures, we considered the <em>CA1temp</em> criterion much more important, giving it a weight 0.198, and giving <em>CA2soil</em> weight 0.03.</p>
<p>As shown in the resulting map, <strong>spatial geometries located within urban areas, as well as those in large fields near the downstream section of the Teplica River, are identified as more suitable for climate adaptation interventions</strong>. This outcome is primarily due to the significantly higher weight assigned to <em>CA1temp</em>, which has a more direct impact on climate adaptation potential. Consequently, areas currently experiencing higher land surface temperatures are prioritized as key targets for intervention.</p>
<p>We recommend thinking about landscape water retention with all future plans for any interventions in the urban fabric. Moreover, we recommend focusing on implementing climate adaptation measures in the agricultural areas (such as dense vegetation separations strips, which help retain the water in the landscape and have a cooling effect as well.) In urban areas, using softer cooler surfaces and adding shadow can be beneficial, as well as adding more wet greenery (perhaps native flood plain biotopes), that improves the local microclimate.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDA_conclusions_CA.png" class="img-fluid figure-img"></p>
<figcaption>MCDA Climate adaptation conclusion (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="quality-of-life" class="level3">
<h3 class="anchored" data-anchor-id="quality-of-life">Quality of life</h3>
<p><strong>What types of places should be created in the stream flood plain?</strong> -&gt; What areas to target for improving quality of life?</p>
<p>In this chapter, we analyse the suitability of analysis geometry spatial units for interventions targeting quality of life objectives. The examined characteristics are:</p>
<ul>
<li><p>Local centrality potential –&gt; prioritise creating central community functions in areas with high local centrality potential (determined by Angular choice analysis).</p></li>
<li><p>Global centrality potential –&gt; prioritise creating central urban functions in areas with high global centrality potential (determined by Angular choice analysis).</p></li>
<li><p>Need for green –&gt; prioritise measures creating accessible urban green areas in spaces where the surrounding buildings lack access to green.</p></li>
</ul>
<section id="ql1acl-where-is-potential-for-community-functions" class="level4">
<h4 class="anchored" data-anchor-id="ql1acl-where-is-potential-for-community-functions"><em>QL1acl</em> – Where is potential for community functions?</h4>
<section id="data-5" class="level5">
<h5 class="anchored" data-anchor-id="data-5">Data</h5>
<section id="angular-choice-analysis" class="level6">
<h6 class="anchored" data-anchor-id="angular-choice-analysis">Angular choice analysis</h6>
<p>To determine spatial potential for community functions, we used Angular Choice analysis. It belongs to Space Syntax analysis, a set of techniques analysing spatial potential. Angular choice analyses every choice of path on a path network from every origin to every destination and calculates how many possible routes go through each location, showing the spatial potential for centralities. It does not take into account the meanings of spaces, but only the structure of the network.</p>
</section>
<section id="results-of-local-angular-choice-analysis-in-senica" class="level6">
<h6 class="anchored" data-anchor-id="results-of-local-angular-choice-analysis-in-senica">Results of local Angular choice analysis in Senica</h6>
<p>Angular choice analysis was executed on OSM street network using the <a href="https://smog.chalmers.se/projects/pst-plugin-for-qgis/">PST QGIS plugin</a> (SMOG n.d.). In area there are no clearly fast routes and there are missing pathways along some roads, so we took all roads from the dataset as potentially slow. A radius of 500 m was used, which is the scale of children playing next to their house or corner shops and neighbourhood functions.</p>
<p>The values of Angular choice analysis with radius 500 m were lineary normalised to 0-1 range.</p>
<p>In the map, the areas with high score show the places that have the spatial potential to be very frequented on routes in 500 m radius, and therefore the spatial potential for communal centralities.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/QL1acl_baseanalysis.png" class="img-fluid figure-img"></p>
<figcaption>Potential for local community functions (normalised.) (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="weighting-and-normalisation" class="level5">
<h5 class="anchored" data-anchor-id="weighting-and-normalisation">Weighting and normalisation</h5>
<p>Aggregated as maximum value in polygon, to show the maximum potential in the area. Where there are no intersecting roads (gives result ‘NULL’), 0 was assigned. This aggregate value was lineary normalised to 0-1 range using the expression:</p>
<pre><code>aggregate( 'layer: angular_choice', 'max', "attribute: r=500 m, normalised", intersects($geometry,geometry(@parent)))</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDA_conclusions_QL1acl.png" class="img-fluid figure-img"></p>
<figcaption>Criterion QL1acl – Community function potential (normalised.) (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="ql2acg-where-is-potential-for-central-functions" class="level4">
<h4 class="anchored" data-anchor-id="ql2acg-where-is-potential-for-central-functions"><em>QL2acg</em> – Where is potential for “central” functions?</h4>
<section id="data-6" class="level5">
<h5 class="anchored" data-anchor-id="data-6">Data</h5>
<section id="angular-choice-analysis-1" class="level6">
<h6 class="anchored" data-anchor-id="angular-choice-analysis-1">Angular choice analysis</h6>
<p>To determine spatial potential for central urban functions, we used Angular Choice analysis, see <a href="#angular-choice-analysis">Angular choice analysis</a> for explanation.</p>
</section>
<section id="results-of-angular-choice-analysis-with-larger-radii-in-senica" class="level6">
<h6 class="anchored" data-anchor-id="results-of-angular-choice-analysis-with-larger-radii-in-senica">Results of Angular choice analysis with larger radii in Senica</h6>
<p>Angular choice analysis was calculated using the <a href="https://smog.chalmers.se/projects/pst-plugin-for-qgis/">PST QGIS plugin</a> (SMOG n.d.) for radii 1 km (local scale of walking to a shop or walking the dog) and 2 km (end of walkable scale). First, these two attributes were normalised. Then these values were combined to a common indicator, giving larger weight to the larger radius:</p>
<div class="line-block">AC1km2km = 1*(AC r=1km) + 2*(AC r=2km)</div>
<p>This attribute was then lineary normalised to 0-1.</p>
<p>In the map, the areas with high score show the places that have the spatial potential to be very frequented on routes in 1000-2000 m radius, and therefore the spatial potential for town-wide centralities.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/QL2acg_baseanalysis.png" class="img-fluid figure-img"></p>
<figcaption>Potential for central urban functions (normalised.) (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="aggregation-and-normalisation-4" class="level5">
<h5 class="anchored" data-anchor-id="aggregation-and-normalisation-4">Aggregation and normalisation</h5>
<p>Again, the value was aggregated by calculating maximum value in the polygon, to show the maximal potential in the area, and lineary normalised to 0-1 range by the following expression:</p>
<pre><code>aggregate( 'layer: angular_choice', 'max', "attribute: AC1km2km, normalised", intersects($geometry,geometry(@parent)))</code></pre>
<p>As the river flows through the city center, it is not surprising that the values are quite high.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDA_conclusions_QL2acg.png" class="img-fluid figure-img"></p>
<figcaption>Criterion QL2acg – Central urban function potential (normalised.) (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="ql3gr-where-is-a-large-need-for-green" class="level4">
<h4 class="anchored" data-anchor-id="ql3gr-where-is-a-large-need-for-green"><em>QL3gr</em> – Where is a large need for green?</h4>
<section id="data-7" class="level5">
<h5 class="anchored" data-anchor-id="data-7">Data</h5>
<section id="attraction-reach-analysis" class="level6">
<h6 class="anchored" data-anchor-id="attraction-reach-analysis">Attraction reach analysis</h6>
<p>Attraction reach analysis is also a part of Space Syntax analysis. It evaluates the potential attraction density that is reachable from location (in our case, the attractions are OSM green areas, and the locations center points of buildings.) Attraction reach evaluates the reachable potential attraction density through a given path network based on its spatial conditions (we use the same OSM road network as for <em>QL1acl</em> and <em>QL2acg</em>.)</p>
</section>
<section id="results-of-attraction-reach-analysis-in-senica" class="level6">
<h6 class="anchored" data-anchor-id="results-of-attraction-reach-analysis-in-senica">Results of Attraction reach analysis in Senica</h6>
<p>Attraction reach was calculated using the <a href="https://smog.chalmers.se/projects/pst-plugin-for-qgis/">PST QGIS plugin</a> (SMOG n.d.) from centroids of buildings to green areas, as classified in OSM, and weighted by the area of the green area. Value was lineary normalised to 0-1, inverting the value, giving high normalised scores to buildings with low attraction reach – showing the need for green, instead of the originally calculated accessibility of it.</p>
<p>In the map, the buildings with high score are the ones with low potential reachability of (large) green spaces, we consider them as lacking connection to green.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/QL3gr_baseanalysis.png" class="img-fluid figure-img"></p>
<figcaption>Attraction reach to green areas (normalised). (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="aggregation-and-normalisation-5" class="level5">
<h5 class="anchored" data-anchor-id="aggregation-and-normalisation-5">Aggregation and normalisation</h5>
<p>Analysis geometry polygons was buffered by 500 m, to simulate area in 500 m walking distance of each polygon. (While technically not 500 m walking distance, on this small scale we consider the difference negligible.) (If replicating this workflow, consider using a 500 m walking distance service area instead, which captures the intended meaning of the analysis more accurately.)</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/QL3gr_bufferedpolygons.png" class="img-fluid figure-img"></p>
<figcaption>Buffered analysis geometry (by Viola Ebermannová)</figcaption>
</figure>
</div>
<p>Then, we filtered out houses that we consider “need green”. Unfortunately, many houses in this area have “type” ‘NULL’, which skews the analysis.</p>
<pre><code>CASE
  WHEN
    "type" IS  NULL OR "type" IS 'apartments' OR "type" IS 'detached' OR "type" IS 'dormitory' OR "type" IS 'farm_auxiliary' OR "type" IS 'government' OR "type" IS 'house' OR "type" IS 'manor' OR "type" IS 'office' OR "type" IS 'public' OR "type" IS 'residential' OR "type" IS 'school' OR "type" IS 'semidetached_house'
    
  THEN 1
  
  ELSE 0

END</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/QL3gr_buildingsneedgreen.png" class="img-fluid figure-img"></p>
<figcaption>Buildings that we consider need green (by Viola Ebermannová)</figcaption>
</figure>
</div>
<p>Then, for each buffered Analysis geometry polygon, sum was calculated of values from buildings in need of green intersecting it (value polygons with no intersecting buildings is zero).</p>
<pre><code>aggregate( 'layer: Buildings in need of green', 'sum', "Attraction reach to green areas, weighted by area, normalised", intersects($geometry,geometry(@parent)))</code></pre>
<p>This was lineary normalised to 0-1 into the final value.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDA_conclusions_QL3gr.png" class="img-fluid figure-img"></p>
<figcaption>Criterion QL3gr – need for green (normalised.) (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="weighting-3" class="level4">
<h4 class="anchored" data-anchor-id="weighting-3">Weighting</h4>
<p>An overall pairwise comparison matrix was created for all indicators at once (see more above). For comparing quality of life criteria among each other, the values were given as follows (accessible urban green has the overall highest priority, and QL2acg has more priority than QL1acl, because of central urban functions servicing more people):</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/QL_SaatyMatrix.png" class="img-fluid figure-img"></p>
<figcaption>Partial pairwise comparison matrix – quality of life (screenshot from <a href="https://fuzzyahp.holecekp.eu/en/">Fuzzy AHP</a> (Holeček n.d.))</figcaption>
</figure>
</div>
<p>The calculated weights for climate adaptation criteria are:</p>
<table class="caption-top table">
<caption>Weights of climate adaptation criteria</caption>
<thead>
<tr class="header">
<th>Criterion</th>
<th>Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>QL1acl</td>
<td>0.098</td>
</tr>
<tr class="even">
<td>QL2acg</td>
<td>0.235</td>
</tr>
<tr class="odd">
<td>QL3gr</td>
<td>0.27</td>
</tr>
</tbody>
</table>
</section>
<section id="quality-of-life-conclusion" class="level4">
<h4 class="anchored" data-anchor-id="quality-of-life-conclusion">Quality of life conclusion</h4>
<p>We weighted 3 criteria targeting improving quality of life in Senica: potential for community functions (QL1acl), potential for central urban functions (QL2acg), and need for green space (QL3gr). QL3gr was given the highest priority with a weight of 0.27, reflecting the potential of the river flood plain to act as a natural recreational area. Potential for central urban functions was given a weight 0.235, more than twice as high as QL1acl – central urban functions serve the whole town community, which makes them important.</p>
<p>It needs to be noted that the layers of QL1acl and QL2acg overlap quite well, because they highlight in general the areas where there are roads, which is also why in the conclusion map, roads generally have higher potential. This does not mean that all roads should be prioritised, but merely that these are the areas to consider when intending to create urban central functions.</p>
<p><strong>Overall highest scores can be found in urban areas in the town, especially in the north side where there already are multiple central functions</strong>. Interventions should be aimed at embracing the location of these centralities, or new ones created, within the river basin, and profiting from the recreational opportunities it brings. Also, in general we recommend to use the biocorridor as an urban green area, and improve connectivity to urban green areas.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDA_conclusions_QL.png" class="img-fluid figure-img"></p>
<figcaption>MCDA Quality of life conclusion (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="mcda-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="mcda-conclusion">MCDA conclusion</h3>
<p>We achieved the final conclusion by calculating the sum of all criteria for each polygon. This shows which areas have over all the greatest potentials and should be prioritised when making decisions on where to target urban stream restoration interventions. However, that does not mean that the areas with low priority should not be targeted. Sustainable stream restoration should be designed in a complex way, for the larger site (stream flood plain) as a whole.</p>
<p>Here is a reminder of the weights assigned to each attribute:</p>
<table class="caption-top table">
<caption>Weights of MCDA criteria</caption>
<thead>
<tr class="header">
<th>Criterion</th>
<th>Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>B1uses</td>
<td>0.058</td>
</tr>
<tr class="even">
<td>B2pot</td>
<td>0.027</td>
</tr>
<tr class="odd">
<td>B3ndvi</td>
<td>0.083</td>
</tr>
<tr class="even">
<td>CA1temp</td>
<td>0.198</td>
</tr>
<tr class="odd">
<td>CA2soil</td>
<td>0.03</td>
</tr>
<tr class="even">
<td>QL1acl</td>
<td>0.098</td>
</tr>
<tr class="odd">
<td>QL2acg</td>
<td>0.235</td>
</tr>
<tr class="even">
<td>QL3gr</td>
<td>0.27</td>
</tr>
</tbody>
</table>
<p>When assigning the weights, we gave highest priority to criteria that directly influence liveability and, in our opinion, offer very actionable basis for feasible and tenable investments (QL3gr, QL2acg, CA1temp). This approach is visible in the results: overall the highest score was achieved in well accessible urban areas, mainly in the east of the town.</p>
<p>This map should be interpreted in the context of the whole analysis, and interventions should be designed to suit the needs of specific locations.</p>
<p>We recommend accessibility of green areas to be improved in the urban space, and where no potentially accessible green spaces exist, we propose to transform the area around the river into a recreational green area that contributes to landscape water retention, native biodiversity, and has a cooling effect. Smaller measures with the same aim can be taken, i.e.&nbsp;local improvements to streets and public space to include more green, permeable, and wet surfaces with greenery improving local microclimate and providing shadow. It can also be beneficial to combine investing into profitable central urban functions in combination with public space and greenery quality improvement. Investment into the central functions can also lead to secondary improvements of adjacent areas, that could be following the findings of this analysis.</p>
<p>Analysis is further concluded in the <a href="#results">Results</a>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDA_conclusions_sum.png" class="img-fluid figure-img"></p>
<figcaption>MCDA Final conclusion (by Viola Ebermannová)</figcaption>
</figure>
</div>
</section>
</section>
<section id="typology-construction" class="level2">
<h2 class="anchored" data-anchor-id="typology-construction">Typology Construction</h2>
<section id="clustering" class="level3">
<h3 class="anchored" data-anchor-id="clustering">Clustering</h3>
<p>The typology construction is based on the course’s provided tutorial on how to construct urban typologies in R. We use K-means Clustering, an unsupervised machine learning method, to find similar typologies for areas around an urban stream based on earlier analysed qualities. The main goal for the typological clustering is to get types of areas that can make it easier to create example design interventions. Perhaps something like “areas with large potential for community facilities with water retention function”, “areas with community functions and maintained high biodiversity”, “areas with biodiversity boost, improved surface permeability and connectivity”. We feel like our goal for typology alligns pretty well with our main research question <em>How to approach stream restoration so that it gives place for desired urban and community facilities, as well as improving native biodiversity, ecological connectivity, and water retention in the landscape?</em></p>
<section id="focus-area-and-variables" class="level4">
<h4 class="anchored" data-anchor-id="focus-area-and-variables">Focus area and variables</h4>
<p>The focus area of the typology clustering is the stream corridor in Senica and the spatial unit is the earlier defined analysis geometries. For the typology clustering, we use four variables that were previously analysed, namely:</p>
<p><code>B1uses</code> - Normalised scores based on the connectivity of an area to ÚSES (the regional ecological stability system). The higher the connectivity, the higher the score.</p>
<p><code>B3ndvi</code> - Normalised scores based on the current “lower health/density” state of vegetation in an area, as indicated by NDVI (Normalised Difference Vegetation Index). The lower the NDVI, the higher the score (high and lush vegetation has lower score.)</p>
<p><code>CA1temp</code> - Normalised scores based on the mean LST (Land Surface Temperature) of an area. The higher the temperature, the higher the score.</p>
<p><code>QL2acg</code> - Normalised scores based on the potential of an area for “central urban” functions.The higher the maximum angular choice within spatial unit, the higher the score.</p>
<p>These specific attributes were chosen, because we judged them to be the most relevant for typology clustering. Both biodiversity attributes (B1uses and B3ndvi) give information about the areas and their current characteristics, making them useful for typology clustering. The other two attributes (CA1temp and QL2acg) got a high weight in the MCDA and are thus important to our research question. Another attribute that scored high in the MCDA is QL3gr, indicating spaces that lack green area within a radius of 500m. This attribute has been left out of the typology construction, since the presence and quality of green areas is already included in attribute B3ndvi and we judged B3ndvi to be more about the area itself than QL3gr, which takes into account the surroundings as well.</p>
</section>
</section>
<section id="workflow" class="level3">
<h3 class="anchored" data-anchor-id="workflow">Workflow</h3>
<p>The dataset that is used, is an aggregated dataset containing all normalised attributes for each analysis geometry. The clustering steps can be generally described as follows:</p>
<p><a href="#step-1.-load-r-packages-and-data">Step 1. Load R packages and data</a><br>
<a href="#step-2.-standardization">Step 2. Standardization</a><br>
<a href="#step-3-determine-the-optimal-k">Step 3: Determine the optimal K</a><br>
<a href="#step-4.-run-k-means-clustering">Step 4. Run K-means clustering</a><br>
<a href="#step-5.-interpret-cluster-centers">Step 5. Interpret cluster centers</a><br>
<a href="#step-6.-optional-calculate-distance-to-cluster-center">Step 6. (Optional) Calculate distance to cluster center</a></p>
<section id="step-1.-load-r-packages-and-data" class="level4">
<h4 class="anchored" data-anchor-id="step-1.-load-r-packages-and-data">Step 1. Load R packages and data</h4>
<p>First, install the necessary R packages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("sf") </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("dplyr")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, load the required packages:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf) <span class="co"># for processing vector data </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Linking to GEOS 3.13.1, GDAL 3.10.2, PROJ 9.5.1; sf_use_s2() is TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="co"># for selecting and transforming data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Read the dataset from the GeoPackage file and display the first few rows using head()</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>grids <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/analysisgeometry_aggregated_allattributes.gpkg"</span>, <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows of the data</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(grids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 10 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 668535.9 ymin: 5392994 xmax: 669132.2 ymax: 5393061
Projected CRS: ETRS89 / UTM zone 33N
               name id_loc_int       QL3gr    QL1acl    QL2acg B1uses B2pot
1 biocorridorriver1          1 0.000000000 0.1959299 0.8273824      1   0.6
2 biocorridorriver1          3 0.000000000 0.2833527 0.8273824      1   0.6
3 biocorridorriver1          2 0.000000000 0.0000000 0.0000000      1   0.6
4 biocorridorriver1         13 0.000000000 0.3913989 0.7737928      1   0.6
5 biocorridorriver1         12 0.000000000 0.0000000 0.0000000      1   0.6
6 biocorridorriver1         20 0.003518765 0.4319898 0.8302794      1   0.6
  B3ndvi CA1temp CA2soil                           geom
1     NA      NA       1 MULTIPOLYGON (((668571.4 53...
2     NA      NA       1 MULTIPOLYGON (((668583.8 53...
3     NA      NA       1 MULTIPOLYGON (((668732.6 53...
4     NA      NA       1 MULTIPOLYGON (((668773.7 53...
5     NA      NA       1 MULTIPOLYGON (((668852.4 53...
6     NA      NA       1 MULTIPOLYGON (((668956.7 53...</code></pre>
</div>
</div>
<p>We can check how many analysis geometries are in the file, in our case 600.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count how many analysis geometries we have</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(grids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 600</code></pre>
</div>
</div>
<p>To better understand the data we are working with, we can visualise it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot B1uses</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grids[<span class="st">"B1uses"</span>], <span class="at">border =</span> <span class="cn">NA</span>, <span class="at">main =</span> <span class="st">"B1uses"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot B3ndvi</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grids[<span class="st">"B3ndvi"</span>], <span class="at">border =</span> <span class="cn">NA</span>, <span class="at">main =</span> <span class="st">"B3ndvi"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot CA1temp</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grids[<span class="st">"CA1temp"</span>], <span class="at">border =</span> <span class="cn">NA</span>, <span class="at">main =</span> <span class="st">"CA1temp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot QL2acg</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grids[<span class="st">"QL2acg"</span>], <span class="at">border =</span> <span class="cn">NA</span>, <span class="at">main =</span> <span class="st">"QL2acg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-5-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-2.-standardization" class="level4">
<h4 class="anchored" data-anchor-id="step-2.-standardization">Step 2. Standardization</h4>
<p>From the dataframe, we remove rows with missing (null/NA) values in one of the selected columns. This is needed to properly perform the clustering. We then select the relevant features (B1uses, B3ndvi, CA1temp, QL2acg). These features are standardised to ensure they contribute equally to the clustering algorithm.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove rows with missing (null/na) values to continue clustering </span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>grids <span class="ot">&lt;-</span> grids <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(B1uses, B3ndvi, CA1temp, QL2acg)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>features <span class="ot">&lt;-</span> grids <span class="sc">|&gt;</span> </span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(B1uses, B3ndvi, CA1temp, QL2acg) <span class="sc">|&gt;</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="co"># remove geometry column so we just keep a data table</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>X_scaled <span class="ot">&lt;-</span> <span class="fu">scale</span>(features) <span class="co"># Standardize (mean=0, sd=1) </span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(X_scaled)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     B1uses      B3ndvi     CA1temp     QL2acg
1 0.9753121 -0.37895766  0.49857323 -0.9419790
2 0.9753121 -0.40992017  0.04600715  0.8735885
3 0.9753121 -0.42500734  0.42961078  1.0899902
4 0.9753121 -0.72952948  0.01583608  1.0869220
5 0.9753121 -0.07110532  0.42961078 -0.9419790
6 0.9753121 -0.47565398 -0.38931831 -0.9419790</code></pre>
</div>
</div>
</section>
<section id="step-3-determine-the-optimal-k" class="level4">
<h4 class="anchored" data-anchor-id="step-3-determine-the-optimal-k">Step 3: Determine the optimal K</h4>
<p>We use the <strong>elbow method</strong> to choose a good number of clusters.</p>
<p>For each value of <code>k</code> (e.g.&nbsp;2 to 9), we run K-means and record a value called <strong>inertia</strong> : the total distance between points and their cluster centers. Lower inertia means tighter (better) clusters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize an empty numeric vector to store inertia values </span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>inertia <span class="ot">&lt;-</span> <span class="fu">numeric</span>()</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Try k values from 2 to 9</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>k_values <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">9</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through each k value</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> k_values) {</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  km <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(X_scaled, <span class="at">centers =</span> k, <span class="at">nstart =</span> <span class="dv">20</span>) </span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># tot.withinss is Total within-cluster sum of squares</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># This measures how compact the clusters are: lower is better.</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  inertia <span class="ot">&lt;-</span> <span class="fu">c</span>(inertia, km<span class="sc">$</span>tot.withinss)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine the results into a data frame for plotting</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>elbow_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">k =</span> k_values, <span class="at">inertia =</span> inertia)</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(elbow_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  k   inertia
1 2 1400.4364
2 3 1102.4197
3 4  859.0034
4 5  740.4449
5 6  623.5229
6 7  547.9949
7 8  471.7611
8 9  405.7474</code></pre>
</div>
</div>
<p>The changing of inertia with increasing k is visualised and based on the <em>elbow point</em> we choose the best value for k. After this elbow point, adding more clusters does not add much to the quality of the end results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make the elbow plot</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k_values, inertia,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">"b"</span>,                  <span class="co"># shown both points + lines </span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"darkblue"</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Elbow Method"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-4.-run-k-means-clustering" class="level4">
<h4 class="anchored" data-anchor-id="step-4.-run-k-means-clustering">Step 4. Run K-Means clustering</h4>
<p>Looking at the elbow plot, there is not a very clear elbow point. However, to limit the amount of clusters so that we can later define clear typologies we choose <code>k = 4</code>.<br>
Now we run the K-means algorithm and assign each analysis geometry to one of the four clusters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># `set.seed()` sets the random number generator to a fixed state</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the seed so the clustering result is always the same when re-run</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">0</span>)  <span class="co"># The number 0 is just a fixed choice. You can also use 10, 345, etc.</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose the number of clusters based on the elbow plot</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Run K-means clustering on the standardized data</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>kmeans_result <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(X_scaled, <span class="at">centers =</span> k, <span class="at">nstart =</span> <span class="dv">20</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="co">#print(kmeans_result)</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the cluster labels to the spatial data</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>grids<span class="sc">$</span>cluster <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(kmeans_result<span class="sc">$</span>cluster) <span class="co"># The result kmeans_result$cluster is a list of cluster labels (1 to 4), in the same order as the original rows in X_scaled and grids</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(grids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 11 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 669998.5 ymin: 5392544 xmax: 670467.4 ymax: 5392697
Projected CRS: ETRS89 / UTM zone 33N
               name id_loc_int QL3gr    QL1acl    QL2acg B1uses B2pot    B3ndvi
1 biocorridorriver1         82     0 0.0000000 0.0000000      1   0.6 0.3024099
2 biocorridorriver1         83     0 0.2866132 0.7184709      1   0.6 0.2936403
3 biocorridorriver1         90     0 0.3971186 0.8041071      1   0.6 0.2893672
4 biocorridorriver1         91     0 0.3971186 0.8028929      1   0.6 0.2031165
5 biocorridorriver1         96     0 0.0000000 0.0000000      1   0.6 0.3896038
6 biocorridorriver1         97     0 0.0000000 0.0000000      1   0.6 0.2750224
  CA1temp CA2soil                           geom cluster
1   0.716       1 MULTIPOLYGON (((669998.5 53...       4
2   0.611       1 MULTIPOLYGON (((670038.5 53...       3
3   0.700       1 MULTIPOLYGON (((670149.7 53...       3
4   0.604       1 MULTIPOLYGON (((670232.7 53...       3
5   0.700       1 MULTIPOLYGON (((670323.1 53...       4
6   0.510       1 MULTIPOLYGON (((670421.1 53...       2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Show how many grids fall into each cluster</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">table</span>(grids<span class="sc">$</span>cluster))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3   4 
125 139 117 110 </code></pre>
</div>
</div>
<p>Save the updated analysis geometry data (with a column indicating clusters) to a new GeoPackage file for further analysis and visualisation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#st_write(grids, "data/analysisgeom_aggregated_cluster03.gpkg")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can also visualise it directly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot clusters with base R</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grids[<span class="st">"cluster"</span>], </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Spatial Pattern of Urban Stream Clusters"</span>, </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="cn">NA</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-5.-interpret-cluster-centers" class="level4">
<h4 class="anchored" data-anchor-id="step-5.-interpret-cluster-centers">Step 5. Interpret cluster centers</h4>
<p>Now we look at the center of each cluster. First, we check the values in standardized form. Then, we convert them back to the original units, so they are easier to understand.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the cluster centers (in standardized form)</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>scaled_centers <span class="ot">&lt;-</span> kmeans_result<span class="sc">$</span>centers</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print them</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Cluster centers (standardized):"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Cluster centers (standardized):"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(scaled_centers)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      B1uses     B3ndvi    CA1temp     QL2acg
1 -0.5458306  1.1746584  0.7672854  0.8457834
2  0.3166772 -0.3868650 -0.9239013 -0.9419790
3  0.4046139 -0.4354863 -0.6831455  1.0588248
4 -0.2102649 -0.3827834  1.0221785 -0.8970032</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the centers back to original scale: x * SD + mean</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>original_centers <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">apply</span>(</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  scaled_centers, <span class="dv">1</span>,</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(x) x <span class="sc">*</span> <span class="fu">attr</span>(X_scaled, <span class="st">"scaled:scale"</span>) <span class="sc">+</span> <span class="fu">attr</span>(X_scaled, <span class="st">"scaled:center"</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the real-world values</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Cluster centers (original):"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Cluster centers (original):"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(original_centers)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     B1uses    B3ndvi   CA1temp       QL2acg
1 0.4168000 0.7424451 0.7783440 7.074676e-01
2 0.7474820 0.3001703 0.3859712 7.216450e-16
3 0.7811966 0.2863992 0.4418291 7.917741e-01
4 0.5454545 0.3013264 0.8374818 1.779817e-02</code></pre>
</div>
</div>
<p>We can also calculate the standard deviation for a better insight in the accuracy of the results. The code for this was written with the help of <a href="https://claude.ai/">Claude AI</a>. It is important to note that the standard deviation for attribute QL2acg in cluster 2 seems to be zero, but only because its cluster center also has an extremely low value. In this case, the standard deviation of zero therefore does not necessarily mean that the value is extremely accurate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate standard deviation within each cluster for each attribute</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co"># First, add cluster assignments to the features dataframe</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>features_with_clusters <span class="ot">&lt;-</span> features</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>features_with_clusters<span class="sc">$</span>cluster <span class="ot">&lt;-</span> kmeans_result<span class="sc">$</span>cluster</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate standard deviation for each attribute within each cluster</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>cluster_stds <span class="ot">&lt;-</span> features_with_clusters <span class="sc">%&gt;%</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cluster) <span class="sc">%&gt;%</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">B1uses_std =</span> <span class="fu">sd</span>(B1uses, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">B3ndvi_std =</span> <span class="fu">sd</span>(B3ndvi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">CA1temp_std =</span> <span class="fu">sd</span>(CA1temp, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">QL2acg_std =</span> <span class="fu">sd</span>(QL2acg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">'drop'</span></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Standard deviation within each cluster (original scale):"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Standard deviation within each cluster (original scale):"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cluster_stds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  cluster B1uses_std B3ndvi_std CA1temp_std QL2acg_std
    &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;
1       1      0.361      0.189      0.0854     0.240 
2       2      0.332      0.267      0.116      0     
3       3      0.317      0.192      0.161      0.0729
4       4      0.406      0.141      0.101      0.107 </code></pre>
</div>
</div>
</section>
<section id="step-6.-optional-calculate-distance-to-cluster-center" class="level4">
<h4 class="anchored" data-anchor-id="step-6.-optional-calculate-distance-to-cluster-center">Step 6. (Optional) Calculate distance to cluster center</h4>
<p>Optionally, we can compute the distance of each analysis geometry to the cluster center. This can be used as an indication of how well the geometry fits in its cluster, thus how closely an individual geometry resembles the general typology it is categorised in.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Step 6 (Optional): Compute distance to cluster center</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the cluster center for each row, using the cluster assignment</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>centroids_matrix <span class="ot">&lt;-</span> kmeans_result<span class="sc">$</span>centers[kmeans_result<span class="sc">$</span>cluster, ]</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Euclidean distance between each point and its assigned cluster center</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>grid_distances <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">rowSums</span>((X_scaled <span class="sc">-</span> centroids_matrix)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Save to grids</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>grids<span class="sc">$</span>cluster_dist <span class="ot">&lt;-</span> grid_distances</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(grids<span class="sc">$</span>cluster_dist)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.2968395 0.9446302 1.2510013 0.9494854 1.3623125 0.8529141</code></pre>
</div>
</div>
<p>To get an even better idea of how well each cluster fits, we can also calculate the mean value of the distances to the cluster center for each cluster. This code was also written with the help of <a href="https://claude.ai/">Claude AI</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean distance to cluster center for each cluster</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>mean_distances_per_cluster <span class="ot">&lt;-</span> grids <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cluster) <span class="sc">%&gt;%</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_distance =</span> <span class="fu">mean</span>(cluster_dist, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_geometries =</span> <span class="fu">n</span>(),</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">'drop'</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Mean distance per cluster to cluster center:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Mean distance per cluster to cluster center:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mean_distances_per_cluster)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  cluster mean_distance n_geometries
  &lt;fct&gt;           &lt;dbl&gt;        &lt;int&gt;
1 1                1.26          125
2 2                1.26          139
3 3                1.17          117
4 4                1.17          110</code></pre>
</div>
</div>
</section>
</section>
<section id="typology-construction-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="typology-construction-conclusion">Typology Construction conclusion</h3>
<section id="typology-description" class="level5">
<h5 class="anchored" data-anchor-id="typology-description">Typology description</h5>
<!-- 🔴 🟠 🟡 🟢 🔵 🟣 -->
<p>To interpret the clustering results, we examine the centers of each cluster in the original data scale. The table below shows the (unscaled) cluster center values of each attribute with their standard deviation.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Type</th>
<th>B1uses</th>
<th>B3ndvi</th>
<th>CA1temp</th>
<th>QL2acg</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><p>0.417 🟠</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.36)</p></td>
<td><p>0.742 🔴</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.19)</p></td>
<td><p>0.778 🔴</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.09)</p></td>
<td><p>0.708 🔴</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.24)</p></td>
<td>High B3ndvi, CA1temp, and QL2acg. Low B1uses.</td>
</tr>
<tr class="even">
<td>2</td>
<td><p>0.747 🔴</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.33)</p></td>
<td><p>0.300 🟡</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.27)</p></td>
<td><p>0.386 🟡</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.12)</p></td>
<td><p>7.216e-16 🟣</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.00)</p></td>
<td>High B1uses and extremely low QL2acg</td>
</tr>
<tr class="odd">
<td>3</td>
<td><p>0.781 🔴</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.32)</p></td>
<td><p>0.286 🟢</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.19)</p></td>
<td><p>0.442 🟠</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.16)</p></td>
<td><p>0.792 🔴</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.07)</p></td>
<td>High B1uses and QL2acg, low B3ndvi</td>
</tr>
<tr class="even">
<td>4</td>
<td><p>0.545 🟠</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.41)</p></td>
<td><p>0.301 🟡</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.14)</p></td>
<td><p>0.837 🔴</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.10)</p></td>
<td><p>0.0177 🔵</p>
<p>(<span class="math inline">\(\sigma\)</span> = 0.11)</p></td>
<td>High CA1temp and very low QL2acg</td>
</tr>
</tbody>
</table>
<p>🔴 High<br>
🟠 Medium high<br>
🟡 Medium low<br>
🟢 Low<br>
🔵 Very low<br>
🟣 Extremely low</p>
<p>The mean distance to cluster center for the four clusters is shown in the table below together with the number of geometries in each cluster.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Type</th>
<th>Mean Distance</th>
<th>Number of geometries</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1.260</td>
<td>125</td>
</tr>
<tr class="even">
<td>2</td>
<td>1.264</td>
<td>139</td>
</tr>
<tr class="odd">
<td>3</td>
<td>1.169</td>
<td>117</td>
</tr>
<tr class="even">
<td>4</td>
<td>1.173</td>
<td>110</td>
</tr>
</tbody>
</table>
<p>All four clusters have just about the same level of accuracy, based on the mean distances to the cluster centers. However, when looking at the standard deviations of the different attributes per cluster, we can conclude that the distinctiveness of the clusters is not very high. Especially the B1uses attribute has high standard deviations and the different clusters therefore do not say much about the typology considering this attribute.</p>
<p>Despite that, we managed to combine some characteristics of each cluster to define distinct typologies and come up with strategies of urban stream development for each.</p>
<section id="type-1-urban-area" class="level6">
<h6 class="anchored" data-anchor-id="type-1-urban-area">Type 1 (urban area)</h6>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 74%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>B1uses</td>
<td>Medium high</td>
<td>Not very connected to ÚSES, so biodiversity improvement of less importance</td>
</tr>
<tr class="even">
<td>B3ndvi</td>
<td>High</td>
<td>Could use more green</td>
</tr>
<tr class="odd">
<td>CA1temp</td>
<td>High</td>
<td>Needs improvements against heat stress</td>
</tr>
<tr class="even">
<td>QL2acg</td>
<td>High</td>
<td>Does have potential for central urban functions</td>
</tr>
</tbody>
</table>
<p>Type 1 consist of areas that are not very connected to ÚSES structures, so improvement of biodiversity will be of low priority. When planning urban development initiatives the focus should instead be on quality of life improvement and better climate adaptation. These areas have potential for central urban functions, the development of which can be paired with improvement of public space. After checking the areas of type 1 on a map, we additionally concluded that most type 1 areas are urban area. This lines up with our conclusions about this typology.</p>
</section>
<section id="type-2-finetune-areas-a" class="level6">
<h6 class="anchored" data-anchor-id="type-2-finetune-areas-a">Type 2 (finetune areas a)</h6>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 76%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>B1uses</td>
<td>High</td>
<td>Can use improvement of already existing ÚSES structures, with focus on biodiversity</td>
</tr>
<tr class="even">
<td>B3ndvi</td>
<td>Medium low</td>
<td>Quite good quality of green</td>
</tr>
<tr class="odd">
<td>CA1temp</td>
<td>Medium low</td>
<td>Does not really need cooling</td>
</tr>
<tr class="even">
<td>QL2acg</td>
<td>Extremely low</td>
<td>This value is unexpected, perhaps caused by clustering 0 values in areas without any roads</td>
</tr>
</tbody>
</table>
<p>Type 2 areas score low on B3ndvi, CA1temp, and QL2acg meaning that its green areas are already of good quality, and that they do not have potential for central urban functions (likely because of not having any roads). There is also a low need for cooling, since the land surface temperatures are not too high. The only attribute that could use improvement is B1uses, but even this does not need too much attention. Therefore we suggest improvement of already existing structures in type 2 areas, possibly with native biodiversity oriented ecological interventions that specifically target ÚSES needs. In conclusion, type 2 does not need much drastic improvement and can instead benefit from finetuning and native biodiversity measures.</p>
</section>
<section id="type-3-finetune-areas-b" class="level6">
<h6 class="anchored" data-anchor-id="type-3-finetune-areas-b">Type 3 (finetune areas b)</h6>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>B1uses</td>
<td>High</td>
<td>Good connectivity to ÚSES structures</td>
</tr>
<tr class="even">
<td>B3ndvi</td>
<td>Low</td>
<td>Good quality of green</td>
</tr>
<tr class="odd">
<td>CA1temp</td>
<td>Medium high</td>
<td>Not that much need for cooling</td>
</tr>
<tr class="even">
<td>QL2acg</td>
<td>High</td>
<td>Does have potential for central urban functions</td>
</tr>
</tbody>
</table>
<p>Both B3ndvi and CA1temp score low, which means that there is not much need for cooling which is in line with a good quality of green in the area (B3ndvi). Type 3 areas have a good connectivity to existing ÚSES structures, so they are a good candidate for native biodiversity improvements. As for type 2, this can be done with small interventions. The high value for QL2acg is a bit unexpected, but can possibly be explained by the fact that main roads go through these areas, that naturally have high angular choice, more on that in the general clustering conclusion. In a way, type 2 and type 3 do not differ that much from each other and we suspect that the differences are mostly caused by the presence of main roads, or absence of any roads. Type 2 and 3 will therefore have similar urban stream development priorities and strategies.</p>
</section>
<section id="type-4-fields" class="level6">
<h6 class="anchored" data-anchor-id="type-4-fields">Type 4 (fields)</h6>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>B1uses</td>
<td>Medium high</td>
<td>Moderate connectivity to existing ÚSES structures</td>
</tr>
<tr class="even">
<td>B3ndvi</td>
<td>Medium low</td>
<td>Bad state of vegetation</td>
</tr>
<tr class="odd">
<td>CA1temp</td>
<td>High</td>
<td>In high need of cooling</td>
</tr>
<tr class="even">
<td>QL2acg</td>
<td>Very low</td>
<td>Does not have potential for central urban functions</td>
</tr>
</tbody>
</table>
<p>Type 4 areas are characterised by a bad state of vegetation and a dire need for cooling. There is a moderate connectivity to existing ÚSES structures, and low potential for central urban functions. When checking the location of these type 4 areas, we found out that is it mostly fields. Heat island effects occur a lot above fields. Although the analysis suggests a need for improvement, we argue that the fields have a low priority for developments, since they often already have specified uses (also supported by results of MCDA). However, we do suggest possibly planting small clusters of denser vegetation and trees (<a href="https://cs.wikipedia.org/wiki/Rem%C3%ADzek">remízek</a>). This could improve water retention (and in turn soil quality), microclimate, and biodiversity in the fields.</p>
</section>
</section>
<section id="conclusion" class="level5">
<h5 class="anchored" data-anchor-id="conclusion">Conclusion</h5>
<p>With the use of K-means clustering we managed to define four different area types. However, two of them (types 2 and 3) are very similar in characteristics and improvement strategies. In our analysis for attribute QL2acg, areas without buildings have a value of 0. We suspect that these values messed up the clustering process, specifically for attribute QL2acg. We think that all zero values got put in type 2, all other low values were put in type 4, all highest values got put in type 3 and all remaining values got put in type 1. This probably caused ambiguous results, with the consequence that type 2 and 3 are essentially the same. Despite that, we can classify the types as urban areas that are in need of much improvement (type 1), areas in need of finetuning (types 2 and 3) and fields that should mostly be left as they are (type 4).</p>
</section>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>The Multi Criteria Decision Analysis (MCDA) highlights areas which should be prioritised in evaluating where to implement urban stream restoration interventions targeting biodiversity, climate adaptation, and quality of life. In general, we recommend:</p>
<ul>
<li><p>improving accessibility of urban green areas (improving quality of life)</p></li>
<li><p>creating new green spaces in the flood plain of the river (improving microclimate, landscape retention ability, recreational opportunities, and native biodiversity),</p></li>
<li><p>integrating creation of communal and urban central functions into new green areas and public space improvements (improving quality of life, microclimate, water retention in landscape, biodiversity)</p></li>
<li><p>modifying public space to include more local biodiversity, and more permeable surfaces (improving microclimate, water retention, liveability, native biodiversity)</p></li>
<li><p>adding biodiversity and water retention measures into large agricultural fields, such as dense vegetation islands/strips (climate adaptation, biodiversity)</p></li>
<li><p>designing within the floodplain area to allow for water spillage, reintroducing flood plain biotopes (climate adaptation, native biodiversity)</p></li>
<li><p>prioritising native species and naturally occurring biotopes in any future interventions (climate adaptation, improving biodiversity)</p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src=".\img/MCDA_conclusions_sum.png" class="img-fluid figure-img"></p>
<figcaption>MCDA Final conclusion (by Viola Ebermannová)</figcaption>
</figure>
</div>
<p>The typologies created in Typology construction offer a simplified typology of areas that can act as a basis for an overview of typical spatial intervention sets. The four typologies and the interventions we recommend for them are:</p>
<ul>
<li><p>Type 1 – “urban area” – improving quality of life and climate adaptation through improving public space, potentially also paired with creating new central urban functions</p></li>
<li><p>Type 2 – “finetune areas a”, and type 3 – “finetunes areas b” – improving already existing structures by native biodiversity oriented measures and other fine tuning</p></li>
<li><p>Type 3 – “fields” – fields have an overall low priority for development, however we recommend climate adaptation and biodiversity measures such as dense vegetation islands/strips</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot clusters with base R</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grids[<span class="st">"cluster"</span>], </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Spatial Pattern of Urban Stream Clusters"</span>, </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="cn">NA</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="tying-the-two-analysis-methods-together" class="level3">
<h3 class="anchored" data-anchor-id="tying-the-two-analysis-methods-together">Tying the two analysis methods together</h3>
<p>When comparing the results from MCDA and Typology construction, it is apparent that type 1 (“urban areas”) corresponds to the areas that scored highest in MCDA. This is not surprising, as the criteria that we prioritised in weighting target improvement of the urban environment. This result suggest that overall largest priority in deciding where to intervene should be given to improving green space accessibility, urban functions, and climate adaptation within the town of Senica.</p>
<p>The lowest MCDA scores can be found in mainly type 4 areas (“fields”), and also in type 2 areas (“finetune areas a”, the areas with extremely low need for green – areas likely without buildings). This follows the same logic.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="analysis-geometry-1" class="level3">
<h3 class="anchored" data-anchor-id="analysis-geometry-1">Analysis geometry</h3>
<p>In a way, the morphologically defined manually constructed analysis geometry is the biggest weakness – severely limiting reproducibility and comparability to other analyses – but also the one of the strengths of the project. We believe the benefits (improving accessibility and opportunities for use of results in collaboration on the future design interventions by making the data better readable for locals, and improving actionability by making the results very space-specific) outweigh the costs, and we tried to describe the workflow behind it in detail.</p>
<p>To fulfil the potential of using morphologically defined spatial units, in future research, it would be beneficial to reevaluate if the use of the biocorridor as the spine is appropriate, and what to use instead in areas where ÚSES is not established. With more knowledge of local conditions, the spine could be defined more precisely based on actual state and potential. Also, the floodplain should be defined more precisely, and it would be better to create the spatial units based not only on aerial photos, but also on knowledge of in situ conditions. Ideally, the spatial units would be created in a collaborative process together with local citizens and local stakeholders, as well as experts on natural and built environment. Spatial units defined in this way would offer a more precise, easily interpretable, and actionable analysis.</p>
</section>
<section id="mcda-criteria-selection" class="level3">
<h3 class="anchored" data-anchor-id="mcda-criteria-selection">MCDA criteria selection</h3>
<p>Criteria should be comprehensive and measurable. Set of criteria should be complete, operational, decomposable, non-redundant, and minimal. Although we gave a lot of thought to the selection of criteria, we were limited by the availability of datasets, and also our analysis abilities. This limited the comprehensibility of the criteria, as by using land surface temperature to measure thermal comfort, or angular choice analysis to determine potential for central functions. Criteria <em>B2pot</em> and <em>B3ndvi</em> are partly redundant, because <em>B2pot</em> depends on land cover typology. In future research, the whole set of criteria should be reevaluated and individual criteria should be made more comprehensible.</p>
</section>
<section id="other-notes" class="level3">
<h3 class="anchored" data-anchor-id="other-notes">Other notes</h3>
<p>Land cover typology classification was not based on much evidence, which is something that needs to be improved in possible future research. Also the Improvement potential was evaluated only conceptually and not based in evidence.</p>
<p>It would also be good to highlight more specific intervention possibilities for the different objectives, that are based in research, and show references of related good (and bad) practice.</p>
<p>Overall, for future research, it would be beneficial to use more evidence based classifications and precise data. Perhaps also primary data, which is based in local conditions and collaborative knowledge gathered from locals and various experts.</p>
</section>
<section id="significant-flaws-in-analysis" class="level3">
<h3 class="anchored" data-anchor-id="significant-flaws-in-analysis">Significant flaws in analysis</h3>
<p>In the area, there is a large water body present. This water body was assigned a high value for the normalised <em>B3ndvi</em>, because water has a low NDVI value. That means it is classified as area with a large priority to improve the green cover based on its current state, despite there being no actual green cover. This makes the analysis biased.</p>
<p>In <em>QL2acg</em>, areas with no roads were assigned value 0, and areas with main roads that are technically in the middle of a field were assigned high values. This lead to the clustering being ambiguous. The high values of main roads in the middle of nowhere demonstrate the character of Space Syntax analysis – it is a network analysis based on solely the network spatial structure, which does not take into account the actual structure of the environment and the meanings and values of places. If we used a more complex approach to determining the potential urban centralities taking into account also these characteristics, these areas would have a low score.</p>
<p>Attribute <em>QL3gr</em> would benefit from a more precise selection of buildings in need of green, and also the urban green areas determined by field research, the data from OSM was very limited.</p>
</section>
</section>
<section id="reflection" class="level2">
<h2 class="anchored" data-anchor-id="reflection">Reflection</h2>
<p>This was a good learning experience for us to practice systematic working with QGIS, and learn new MCDA and clustering skills and knowledge. That said, it felt by dispersing the workload among the three team members, we also dispersed the knowledge the individual team members gained.</p>
<p>The limitations on our work and the limited layer selection for attributes stems from us not being able to afford the time to redo certain things and our limited abilities, however we tried to reflect and learn from our mistakes for the future.</p>
<section id="violas-reflection-on-teamwork" class="level4">
<h4 class="anchored" data-anchor-id="violas-reflection-on-teamwork">Viola’s reflection on teamwork</h4>
<p>(This is personal opinion, therefore it is in a dedicated section separated from the collectively produced text.)</p>
<p>From the start, I took the task of coordinating the project. This gave me insight into basically all aspects of this (except calculations with Google Earth Engine, and also I do not have a deep understanding of typology construction.) I am grateful for this, because it allowed me to learn a lot.</p>
<p>It did feel to me that because we separated the tasks so much (with me doing the research design for MCDA and constructing the analysis geometry, Kelly and Hongyue performing the component analyses, and then Kelly doing the typology construction, with me helping with interpretation, and Hongyue focusing on the presentation), not everyone naturally learned about everything in that process. Learning does always rely on personal initiative, but I do feel like we should have shared our workflows and findings among each other more regularly and in a clearer way. (I also think if we were a bigger team, we would have been forced to talk together more and would naturally overlap with our tasks.)</p>
<p>I also think that I learned so much, because I took on a disproportional volume of work and mental load. At the start of the project, it felt a lot like I need to take on the responsibility to have everything in my mind, because it didn’t feel like the collaboration can be effective. Once this happens, it is difficult to transition to the responsibility being shared. Also, personal and health problems in the team contributed to me feeling like I was the only person who could consistently work on the course in a certain part of the quarter. (Also, I think I have quite high standards for my work that I don’t like pushing onto people, and also my other courses allowed me to work on this more than my teammates, so I would rather just do stuff myself – but this is something that also can be communicated about better.)</p>
<p>The collaboration might have been effective on paper, with a functioning distribution of the tasks and efficient to the point conversations, but I think it would have been more fruitful had we discussed more about what we are doing together, instead of me taking the responsibility for so many decisions, even for the price of the discussions taking significantly longer. It would have been better for me to give some of my responsibilities to the whole group as a team, and focus on collaborative communication, so I wouldn’t feel so responsible for the project, and everyone could learn a lot.</p>
</section>
<section id="kellys-reflection-on-teamwork" class="level4">
<h4 class="anchored" data-anchor-id="kellys-reflection-on-teamwork">Kelly’s reflection on teamwork</h4>
<p>For me the progression of this course did not entirely go according to plan. In the beginning, I struggled a bit with fully understanding the assignment and the end goal of our research. Therefore it was hard for me to start working and producing products immediately. Additionally, I also had a lot of work for other courses which made it challenging to find time for a course where it was not entirely clear what I could do to make progress. This is also why I really appreciated Viola taking the lead, creating structure and also taking a lot of work on her plate. Then, I sadly got the flu for some time making it impossible for me to work on this project (or any other university related stuff) at all, which also resulted in me feeling a bit out of the loop. When I got better, I wanted to put the effort in and actively asked for a detailed update on where we stood as a team regarding our progress. This is when I felt like I could finally do my part. The analyses that I did, I really enjoyed and I feel like I learned several new useful skills, besides learning about MCDA and Typology Clustering.</p>
<p>In general, I do feel like this is a pretty big course and it is impossible to learn about everything. For example, the three workshops given in week 3. All of those workshops sounded so interesting but due to limited time it was sadly not feasible to do them all. Even though the workshops did play a significant part in the final analyses. Because I could only follow one of the workshops it was a bit hard for me to understand the results and workings of the analyses performed based on the other two workshops. As a team we could have put more effort into teaching and telling each other about what we learned in the different workshops, so that is something to keep in mind during future courses and group work.</p>
<p>All in all, I wish I could have done more work earlier in the quarter, but I am satisfied with what I managed to do in the end. This course was very interesting, but sadly there was too much information in a limited time period so that not everyone could learn about everything. More communication could have positively effected this though, by sharing more actively what we learned individually.</p>
</section>
</section>
<section id="conclusion-1" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-1">Conclusion</h2>
<p>This report presented a spatial Multi Criteria Data Analysis and Typology Construction to determine possibilities for restoration of the Teplica river in the town Senica (Slovakia). We examined different criteria from the topics of biodiversity, climate adaptation, and quality of life on morphologically defined spatial units in Senica. The MCDA highlighted areas which should be prioritised for urban stream restoration interventions, and also suggested general recommendations for which measures to take in developing areas in the river flood plain. Typology construction led to the definition of four area types, for which we suggested general directions for interventions. These types can be the basis of model examples of sets of interventions.</p>
<p>Although the analysis is not without flaws, it gives good insight into the state of the Teplica river floodplain in regards of the selected criteria and offers ideas for locations and types of possible future sustainable urban stream restoration interventions.</p>
</section>
<section id="appendix" class="level2">
<h2 class="anchored" data-anchor-id="appendix">Appendix</h2>
<p>We include the analyses that we made, but that did not make it into the list of criteria.</p>
<section id="space-syntax-analysis" class="level3">
<h3 class="anchored" data-anchor-id="space-syntax-analysis">Space syntax analysis</h3>
<p>We performed a broader space syntax analysis, before choosing the layers to use for Quality of life criteria. Source of data: OSM.</p>
<p><strong>Angular choice analysis</strong></p>
<iframe src="pdf/99_AngularChoice.pdf" width="100%" height="500" frameborder="0">
</iframe>
<p>Analyses every choice of path from every location to every destination – how many possible routes go through location, showing the spatial potential for centralities.</p>
<ul>
<li><p>500 m</p>
<ul>
<li><p>very local scale, scale of children playing and shops on the corner even on this scale, there are some centralities along the river</p></li>
<li><p>this means the river has a potential to be used by the community and act as a very local common space under social control</p></li>
</ul></li>
<li><p>1000 m</p>
<ul>
<li><p>local scale of walking to shop or walking the dog</p></li>
<li><p>paths along river do not have very low angular choice, hinting at them being possibly moderately frequented</p></li>
<li><p>more centralities at bridges</p></li>
</ul></li>
<li><p>2000m:</p>
<ul>
<li><p>close to the end of walkable scale</p></li>
<li><p>some paths along river in the center have high angular choice, meaning they will likely be more frequented and have potential for active use and ammenities</p></li>
<li><p>more centralities at bridges</p></li>
</ul></li>
</ul>
<p><strong>Attraction reach from buildings to green spaces</strong></p>
<iframe src="pdf/99_AttractionReach_GreenSpace.pdf" width="100%" height="500" frameborder="0">
</iframe>
<p>Analyses the <em>reachable</em> potential <em>attraction density</em> of location (sqm). Green areas sourced from OSM were weighted by area.</p>
<ul>
<li><p>500m:</p>
<ul>
<li><p>very local scale, scale of children playing and shops on the corner</p></li>
<li><p>river and surroundings as potential new green areas to serve local scale in the west and north of the town</p></li>
</ul></li>
<li><p>1000m:</p>
<ul>
<li><p>local scale of walking to shop or walking the dog</p></li>
<li><p>river and surroundings as potential new green areas to serve local scale in the west and north of the town</p></li>
</ul></li>
<li><p>2000m:</p>
<ul>
<li><p>close to the end of walkable scale</p></li>
<li><p>center/east of town not having access to more large areas of green</p></li>
</ul></li>
</ul>
<p><strong>Attraction Reach from buildings to Teplica</strong></p>
<iframe src="pdf/99_AttractionReach_Teplica.pdf" width="100%" height="500" frameborder="0">
</iframe>
<p>Analyses the <em>reachable</em> potential <em>attraction density</em> of location (sqm), was measured to points every 5m of waterway.</p>
<ul>
<li><p>500m:</p>
<ul>
<li><p>very local scale, scale of children playing and shops on the corner</p></li>
<li><p>Teplica quite well accessible from houses</p></li>
<li><p>SW: industry is not so well connected</p></li>
<li><p>SE: lacking connection between road parallel to river</p></li>
</ul></li>
<li><p>1000m:</p>
<ul>
<li><p>local scale of walking to shop or walking the dog</p></li>
<li><p>SW industry not allowing houses behind it to access river</p></li>
<li><p>SE: still visible missing connection between parallel road and river</p></li>
</ul></li>
<li><p>2000m:</p>
<ul>
<li><p>close to the end of walkable scale</p></li>
<li><p>very similar to 1k</p></li>
<li><p>SW: industry finally permeable, however this is quite a large distance and if the river and the way to it are not nice, there are no reasons to go</p></li>
<li><p>W: the small village is not connected to a large path of the river, that is why it is lighter</p></li>
<li><p>SE: still visible missing connection between parallel road and river</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="sources" class="level2">
<h2 class="anchored" data-anchor-id="sources">Sources</h2>
<section id="literature" class="level3">
<h3 class="anchored" data-anchor-id="literature">Literature</h3>
<p>Agrointeg. (n.d.). Hydrologické funkce půdy. AGROINTEG, s.r.o. Retrieved June 21, 2025 from <a href="https://www.agrointeg.cz/technologie-pro-kompostovani/hydrologicke-funkce-pudy" class="uri">https://www.agrointeg.cz/technologie-pro-kompostovani/hydrologicke-funkce-pudy</a></p>
<p>Holeček, P. (n.d.). Fuzzy AHP. Web Application. Screenshots taken on June 10 from <a href="https://fuzzyahp.holecekp.eu/en/" class="uri">https://fuzzyahp.holecekp.eu/en/</a></p>
<p>Intersucho. (2025). Aktuálny stav sucha na Slovensku. (Current drought state in Slovakia.) Ústav výzkumu globální změny AV ČR. (Global Change Research Institute CAS). Retrieved June 21, 2025 from <a href="https://www.intersucho.sk/sk/?mapcountry=sk&amp;from=2024-06-21&amp;to=2025-06-21&amp;current=2024-10-06" class="uri">https://www.intersucho.sk/sk/?mapcountry=sk&amp;from=2024-06-21&amp;to=2025-06-21&amp;current=2024-10-06</a></p>
<p>Mesto Senica. (19 May 2025). Demografia – Demografický vývoj v meste Senica. (Demography – Demographical development in the town Senica). Retrieved on June 21, 2025 from <a href="https://senica.sk/clanok/demografia" class="uri">https://senica.sk/clanok/demografia</a></p>
<p>ReBioClim. (n.d.) ReBioClim - ProjectOverview. Interreg Central Europe. Retrieved June 20, 2025 from <a href="https://www.interreg-central.eu/projects/rebioclim/" class="uri">https://www.interreg-central.eu/projects/rebioclim/</a></p>
<p>SAŽP. (n.d.). Územný systém ekologickej stability (ÚSES). SAŽP – Slovak Environment Agency. Retrieved on June 6, 2025 from <a href="https://www.sazp.sk/zivotne-prostredie/starostlivost-o-krajinu/zelena-infrastruktura/uzemny-system-ekologickej-stability-uses" class="uri">https://www.sazp.sk/zivotne-prostredie/starostlivost-o-krajinu/zelena-infrastruktura/uzemny-system-ekologickej-stability-uses</a></p>
<p>Suchá, K. (2021). Retention capacity of soils and landscape possibilities of its increase in conditions of climate change. In <em>Dissertation Thesis</em> [Thesis]. <a href="https://www.shmu.sk/File/KMO/SuchaK_Retencni_schop_pud_krajiny_jej_zvys_podm_klimat_zmeny.pdf" class="uri">https://www.shmu.sk/File/KMO/SuchaK_Retencni_schop_pud_krajiny_jej_zvys_podm_klimat_zmeny.pdf</a></p>
<p>Šachová, B. (2010). Hydrologické sucho v kontextu klimatické změny ve světě a v českém povodí Labe. (Hydrological drought in the context of climatic changes in the world and in the Czech part of Elbe River basin). Bachelor thesis supervised By J. Kocum. <a href="https://dspace.cuni.cz/bitstream/handle/20.500.11956/39621/BPTX_2009_1_11310_0_199808_0_78696.pdf?sequence=1&amp;isAllowed=y" class="uri">https://dspace.cuni.cz/bitstream/handle/20.500.11956/39621/BPTX_2009_1_11310_0_199808_0_78696.pdf?sequence=1&amp;isAllowed=y</a></p>
<p>USGS. (n.d.). Landsat Normalized Difference Vegetation Index. Retrieved June 21, 2025 from <a href="https://www.usgs.gov/landsat-missions/landsat-normalized-difference-vegetation-index" class="uri">https://www.usgs.gov/landsat-missions/landsat-normalized-difference-vegetation-index</a></p>
</section>
<section id="map-layers" class="level3">
<h3 class="anchored" data-anchor-id="map-layers">Map layers</h3>
<p>Bing Aerial Photos. (2018). Retrieved from <a href="http://ecn.t3.tiles.virtualearth.net/tiles/a%7Bq%7D.jpeg?g=1" class="uri">http://ecn.t3.tiles.virtualearth.net/tiles/a%7Bq%7D.jpeg?g=1</a></p>
<p>European Union/ESA/Copernicus. (2025) Harmonized Sentinel-2 MSI, Level -2A. Retrieved June 6, 2025 from Google Earth Engine</p>
<p>Google Earth Engine. (2025) Cloud Score+ S2_HARMONIZED V1. Retrieved June 6, 2025 from Google Earth Engine</p>
<p>NASA / USGS / JPL-Caltech. (2025) NASA SRTM Digital Elevation 30m. Retrieved June 6, 2025 from Google Earth Engine</p>
<p>OSM. Open street map. <a href="https://www.openstreetmap.org" class="uri">https://www.openstreetmap.org</a></p>
<p>SAŽP (Slovak Environment Agency) (2002-2024). Atlas krajiny Slovenskej republiky. (Atlas of the landscape of the Slovak Republic). Accessible through <a href="https://www.enviroportal.sk/atlas-krajiny-sr" class="uri">https://www.enviroportal.sk/atlas-krajiny-sr</a></p>
<p>SMOG – Spatial morphology group Chalmers School of Architecture. (n.d.) PST plugin for QGIS – An open source tool for performing spatial analyses. Developed by: KTH School of Architecture, Chalmers School of Architecture (SMoG) and Spacescape AB. Alexander Ståhle, Lars Marcus, Daniel Koch, Martin Fitger, Ann Legeby, Gianna Stavroulaki, Meta Berghauser Pont, Anders Karlström, Pablo Miranda Carranza, Tobias Nordström. Accessible through <a href="https://smog.chalmers.se/projects/pst-plugin-for-qgis/" class="uri">https://smog.chalmers.se/projects/pst-plugin-for-qgis/</a></p>
<p>SVP š.p. – Slovakian Water Management Utility. (15 June 2023). Mapy povodňového ohrozenia. (Flood danger maps). Retrieved June 1, 2025 from: <a href="https://mpt.svp.sk/svp_vmapportal/?basemap=orto2023&amp;zoom=5&amp;lat=48.683285&amp;lng=17.339609" class="uri">https://mpt.svp.sk/svp_vmapportal/?basemap=orto2023&amp;zoom=5&amp;lat=48.683285&amp;lng=17.339609</a></p>
<p>ÚGKK SK. (n.d.). Katastrálna mapa (Cadaster map), Mapa určeného operátu (Cadaster parcels usually not visible in the terrain merged into larger units). Portál elektronických služieb katastra nehnuteľností. (Portal for Electronic Services of the Cadaster). Úřad geodézie, kartografie a katastra Slovenskej reoubliky. (Office for geodesy, cartography, and cadaster of the Slovak Reoublic). Retrieved from <a href="https://kataster.skgeodesy.sk/eskn/rest/services/" class="uri">https://kataster.skgeodesy.sk/eskn/rest/services/</a></p>
<p>USGS. (2025) USGS Landsat 9 Level 2, Collection 2, Tier 1. Retrieved June 6, 2025 from Google Earth Engine</p>
<p>USGS. (2025) USGS Landsat 8 Level 2, Collection 2, Tier 1. Retrieved June 6, 2025 from Google Earth Engine</p>
</section>
<section id="images" class="level3">
<h3 class="anchored" data-anchor-id="images">Images</h3>
<p>Street View of Senica – Google Maps. (May 2012). Retrieved on May 22, 2025 from: <a href="https://www.google.com/maps/place/905+01+Senica,+Slovensko/@48.6841521,17.3581313,3a,75y,296.73h,88.04t/data=!3m7!1e1!3m5!1sbkMc3aSUkJxRvi5IszgGWg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D1.9640483562330928%26panoid%3DbkMc3aSUkJxRvi5IszgGWg%26yaw%3D296.73281886129774!7i13312!8i6656!4m7!3m6!1s0x476cb4e2e7ed1a27:0x400f7d1c696ee40!8m2!3d48.6811502!4d17.3672337!10e5!16zL20vMGRyeG43?entry=ttu&amp;g_ep=EgoyMDI1MDUyMS4wIKXMDSoASAFQAw%3D%3D" class="uri">https://www.google.com/maps/place/905+01+Senica,+Slovensko/@48.6841521,17.3581313,3a,75y,296.73h,88.04t/data=!3m7!1e1!3m5!1sbkMc3aSUkJxRvi5IszgGWg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D1.9640483562330928%26panoid%3DbkMc3aSUkJxRvi5IszgGWg%26yaw%3D296.73281886129774!7i13312!8i6656!4m7!3m6!1s0x476cb4e2e7ed1a27:0x400f7d1c696ee40!8m2!3d48.6811502!4d17.3672337!10e5!16zL20vMGRyeG43?entry=ttu&amp;g_ep=EgoyMDI1MDUyMS4wIKXMDSoASAFQAw%3D%3D</a></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>